### ISSUE TITLE
Display source rather than object files when compiling

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#1018]
Dan Grayson noted that we have:

make[3]: Entering directory '/Users/dan/src/M2/M2.git/M2/BUILD/dan/builds.tmp/gallium-development.debug/libraries/flint/build/flint2-2.8.3/fq_poly_factor'
    CC   ../build/fq_poly_factor/fq_poly_factor_clear.o
    CC   ../build/fq_poly_factor/fq_poly_factor_concat.o
    CC   ../build/fq_poly_factor/fq_poly_factor_factor.o
    CC   ../build/fq_poly_factor/fq_poly_factor_factor_berlekamp.o
    CC   ../build/fq_poly_factor/fq_poly_factor_factor_cantor_zassenhaus.o

rather than showing the source file being compiled.

**Comment by wbhart** [comment]
I don't know how to do this. If I change QUIET_CC to use $< instead of $@ in both Makefile.in and Makefile.subdirs it prints .c for all the files except the last one in the module. And it only prints the filename itself, not its path (which may not actually be a problem).

@albinahlback How is that makefu? Do you have any idea how this is supposed to be done?

**Comment by albinahlback** [comment]
It is easy when you write it without the use of Makefile.subdirs. I can fix this (however, I'm currently fixing all the headers, which takes A LOT of time, so don't know when I can fix this).

**Comment by wbhart** [comment]
Ok, then I can just leave that until you try rewriting the Makefile stuff. That was put off until the next release right?
