### ISSUE TITLE
Split out NTL interface to a separate project

### ISSUE THREAD

**Issue by mkoeppe** [flintlib/flint#1039]
Currently downstream packagers of FLINT have to decide whether they enable NTL support in FLINT or not.
If they do, all projects that use the packaged FLINT library pull in NTL as well.

Removing the NTL interface from FLINT (and putting it in a separate small project that depends on FLINT and NTL) would solve this; and as well would simplify the build systems of FLINT.

**Comment by albinahlback** [comment]
@fredrik-johansson what is your opinion on this? I am for it.

**Comment by mkoeppe** [comment]
That would be a good solution, I think.
