### ISSUE TITLE
CI for ARM with NEON instructions

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1100]
As of now, it seems like using [this Github action](https://github.com/marketplace/actions/run-on-architecture) seems to be the best option at the moment.

**Comment by isuruf** [comment]
There's also Travis-CI which unlike it's x86_64 offering is free for aarch64 and ppc64le and runs on native hardware.

**Comment by albinahlback** [comment]
Then I will use that! Thanks!

**Comment by wbhart** [comment]
Hmm, free for how long. But yeah, we can use that for now.

**Comment by isuruf** [comment]
AFAIK, the hardware are donations from ARM (linux-aarch64) and IBM (linux-ppc64le and linux-s390x)
and Travis-CI has to keep them free for open source users.

**Comment by wbhart** [comment]
Ah great. Unfortunately I guess this means they are not useful for testing Apple Silicon?

**Comment by isuruf** [comment]
Yes, not useful for Apple Silicon

**Comment by albinahlback** [comment]
Ops, this is a priority due to `fft_small`. Will work on it now.

**Comment by albinahlback** [comment]
https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

**Comment by albinahlback** [comment]
I think I will close this for now. Would be nice to revise once and if Github releases native ARM runners, but that might be years down the line as the beta for these runners is starting in January 2024.
