### ISSUE TITLE
Switch fft from OpenMP to pthreads

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1106]
Seems like `fft.h` uses OpenMP, which suggests it is outdated as we currently use PThreads. What is the status of this directory?

**Comment by wbhart** [comment]
The FFT is in heavy use. Just that we haven't switched from OpenMP to pthreads yet.

**Comment by albinahlback** [comment]
Okay, feel free to close then!

**Comment by wbhart** [comment]
I don't find an open ticket for converting the fft code to pthreads, so I'll just change the title of this one.

**Comment by fredrik-johansson** [comment]
I believe this is no longer the case?
