### ISSUE TITLE
Putting flint_mpn_mul_fft_main to use

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#1117]
It's easy to forget that we have FFT multiplication that isn't being used everywhere.

Would it make sense to do the following?

* Add (and use) ``flint_mpn_mul``, ``flint_mpn_mul_n`` and ``flint_mpn_sqr`` that switch to ``flint_mpn_mul_fft_main`` above some threshold (could be inline functions so that there is no call overhead for small operands)
* Rewrite some ``fmpz`` functions like ``fmpz_mul`` to call our ``flint_mpn`` functions.

We would also need FFT-based division and GCD to really profit, but of course that's a lot more work. It would be easier if GMP just allowed replacing its ``mpn_mul_fft`` at runtime but politically I doubt that will happen.

Out of curiosity, I did a quick test to see how our FFT performs on my machine (8-core Zen3): 

```
#include "flint/fft.h"
#include "flint/profiler.h"

int main()
{
    slong i;
    mp_size_t n;
    int threads;
    mp_ptr a, b, c;

    for (n = 10000; n <= 100000000; n *= 10)
    {
        a = flint_malloc(n * sizeof(mp_limb_t));
        b = flint_malloc(n * sizeof(mp_limb_t));
        c = flint_malloc(2 * n * sizeof(mp_limb_t));

        for (i = 0; i < n; i++)
            a[i] = -i;
        for (i = 0; i < n; i++)
            b[i] = -i-1;

        printf("n = %ld\n", n);
        printf("gmp                     ");
        TIMEIT_START
        mpn_mul(c, a, n, b, n);
        TIMEIT_STOP

        for (threads = 1; threads <= 8; threads *= 2)
        {
            printf("flint, threads = %d      ", threads);
            flint_set_num_threads(threads);
            TIMEIT_START
            flint_mpn_mul_fft_main(c, a, n, b, n);
            TIMEIT_STOP
        }
        printf("\n");

        flint_free(a);
        flint_free(b);
        flint_free(c);
    }
}
```

```
n = 10000
gmp                     cpu/wall(s): 0.00155 0.00155
flint, threads = 1      cpu/wall(s): 0.00137 0.00137
flint, threads = 2      cpu/wall(s): 0.00147 0.00143
flint, threads = 4      cpu/wall(s): 0.0017 0.0015
flint, threads = 8      cpu/wall(s): 0.0021 0.00151

n = 100000
gmp                     cpu/wall(s): 0.0213 0.0213
flint, threads = 1      cpu/wall(s): 0.0189 0.0189
flint, threads = 2      cpu/wall(s): 0.0214 0.012
flint, threads = 4      cpu/wall(s): 0.0248 0.0102
flint, threads = 8      cpu/wall(s): 0.0261 0.0095

n = 1000000
gmp                     cpu/wall(s): 0.354 0.354
flint, threads = 1      cpu/wall(s): 0.293 0.293
flint, threads = 2      cpu/wall(s): 0.301 0.166
flint, threads = 4      cpu/wall(s): 0.304 0.095
flint, threads = 8      cpu/wall(s): 0.687 0.127

n = 10000000
gmp                     cpu/wall(s): 3.825 3.826
flint, threads = 1      cpu/wall(s): 3.301 3.3
flint, threads = 2      cpu/wall(s): 3.444 1.854
flint, threads = 4      cpu/wall(s): 4.006 1.226
flint, threads = 8      cpu/wall(s): 14.509 2.12

n = 100000000
gmp                     cpu/wall(s): 41.282 41.283
flint, threads = 1      cpu/wall(s): 35.812 35.813
flint, threads = 2      cpu/wall(s): 41.568 21.61
flint, threads = 4      cpu/wall(s): 50.08 13.68
flint, threads = 8      cpu/wall(s): 78.396 11.172

```

I'm thinking we should maybe put in some throttle on the number of threads used in the FFT, at least for smaller ``n``, especially considering that``mpn_mul`` is a low-level function that is likely to be competing with other concurrent tasks.

How are the current timings on other machines?

There is a rather significant slowdown with 8 threads at n = 10000000, which is reproducible. Any idea what is going on there?

**Comment by fredrik-johansson** [comment]
See also #924.

**Comment by fredrik-johansson** [comment]
Turns out I was having a power management configuration problem with my computer, i.e. the power cord was not plugged into the wall. Fixing this makes the timing anomaly go away:

```
n = 10000
gmp                     cpu/wall(s): 0.00162 0.00161
flint, threads = 1      cpu/wall(s): 0.00145 0.00145
flint, threads = 2      cpu/wall(s): 0.0015 0.00147
flint, threads = 4      cpu/wall(s): 0.00163 0.0015
flint, threads = 8      cpu/wall(s): 0.00179 0.00147

n = 100000
gmp                     cpu/wall(s): 0.0212 0.0212
flint, threads = 1      cpu/wall(s): 0.0177 0.0177
flint, threads = 2      cpu/wall(s): 0.0201 0.011
flint, threads = 4      cpu/wall(s): 0.0225 0.0088
flint, threads = 8      cpu/wall(s): 0.0265 0.0091

n = 1000000
gmp                     cpu/wall(s): 0.307 0.308
flint, threads = 1      cpu/wall(s): 0.25 0.25
flint, threads = 2      cpu/wall(s): 0.269 0.146
flint, threads = 4      cpu/wall(s): 0.305 0.093
flint, threads = 8      cpu/wall(s): 0.352 0.074

n = 10000000
gmp                     cpu/wall(s): 3.869 3.869
flint, threads = 1      cpu/wall(s): 3.242 3.242
flint, threads = 2      cpu/wall(s): 3.497 1.872
flint, threads = 4      cpu/wall(s): 4.043 1.225
flint, threads = 8      cpu/wall(s): 5.668 0.968

n = 100000000
gmp                     cpu/wall(s): 42.704 42.704
flint, threads = 1      cpu/wall(s): 36.18 36.182
flint, threads = 2      cpu/wall(s): 40.971 21.305
flint, threads = 4      cpu/wall(s): 50.52 13.832
flint, threads = 8      cpu/wall(s): 77.041 11.02
```

**Comment by albinahlback** [comment]
When linking against `__gmpn_nussbaumer_mul` instead of `mpn_mul`, I get these results:
```
n = 10000
gmp                     cpu/wall(s): 0.0019 0.0019
flint, threads = 1      cpu/wall(s): 0.00202 0.00202
flint, threads = 2      cpu/wall(s): 0.00209 0.00203
flint, threads = 4      cpu/wall(s): 0.00232 0.00208
flint, threads = 8      cpu/wall(s): 0.0027 0.00211

n = 100000
gmp                     cpu/wall(s): 0.0281 0.0282
flint, threads = 1      cpu/wall(s): 0.0249 0.0249
flint, threads = 2      cpu/wall(s): 0.0285 0.0156
flint, threads = 4      cpu/wall(s): 0.0346 0.0143
flint, threads = 8      cpu/wall(s): 0.0371 0.0133

n = 1000000
gmp                     cpu/wall(s): 0.4 0.4
flint, threads = 1      cpu/wall(s): 0.315 0.317
flint, threads = 2      cpu/wall(s): 0.341 0.184
flint, threads = 4      cpu/wall(s): 0.434 0.136
flint, threads = 8      cpu/wall(s): 0.6 0.116

n = 10000000
gmp                     cpu/wall(s): 5.04 5.045
flint, threads = 1      cpu/wall(s): 4.41 4.42
flint, threads = 2      cpu/wall(s): 4.574 2.445
flint, threads = 4      cpu/wall(s): 5.435 1.626
flint, threads = 8      cpu/wall(s): 11.51 1.764

n = 100000000
gmp                     cpu/wall(s): 55.584 55.651
flint, threads = 1      cpu/wall(s): 52.882 52.936
flint, threads = 2      cpu/wall(s): 55.932 28.997
flint, threads = 4      cpu/wall(s): 70.361 18.983
flint, threads = 8      cpu/wall(s): 148.867 20.278
```
(I do not have an 8-core cpu. However, it is 8-threaded.)

**Comment by wbhart** [comment]
It is easy to forget. I could have sworn we used it more widely.

It is currently used in KS and mullow_KS which are the integer polynomial functions that should make use of it. Of course nmod_poly_mul also uses KS as do various other things.

But yeah, I guess more comprehensive use of it could be worthwhile.

The main problem is that checking whether you are over the cutoff for FFT is actually pretty expensive for small inputs, so you might actually notice an overall slowdown of Flint. Presumably this is the reason we did it in the past.

The GMP mul and mul_n functions are pretty sophisticated, hence just reproducing them in Flint is a massive job and not really recommended.

But maybe we should do this anyway, especially now that we have @tthsqe12 's amazing FFT work.

**Comment by wbhart** [comment]
Just in case it isn't obvious, the other main polynomial multiplication (SS) uses the FFT directly.

There are numerous places where division should use the FFT directly, as this can make a factor 2 difference in timing.

However, I think we really need to sort out the fastest possible strategy for nmod_poly_mul first. It's unclear whether an FFT like the one in zn_poly, using the Schoenhage trick would be faster or slower than using CRT with @tthsqe12 's new FFT. This should be tested.

Of course it also makes sense to implement the FFT precaching tricks for division to get that factor of 2 speedup before trying other approaches. Of course if the current approach can be 3x faster with @tthsqe12 's FFT then that would be better than a 2x speedup using precaching. Or perhaps it is even possible to combine the approaches (I didn't check).

**Comment by wbhart** [comment]
I should say Schoenhage trick + REDC, since this is what zn_poly did.

**Comment by fredrik-johansson** [comment]
> The main problem is that checking whether you are over the cutoff for FFT is actually pretty expensive for small inputs, so you might actually notice an overall slowdown of Flint. Presumably this is the reason we did it in the past.

Well, the overhead is 1 predictable branch if implemented as an inline function, so it's only going to matter for really small input. I'm thinking if we switch over functions like fmpz_mul and fmpz_addmul we might want to try inlining the 1-2 limb cases in those functions anywyay.

**Comment by fredrik-johansson** [comment]
I tried changing Arb on the threading branch to use flint_mpn_mul_fft_main instead of mpn_mul, mpn_mul_n or mpn_sqr when n >= 10000 limbs. The improvement is not bad:

    10^7 digits of pi, threads = 1
    old: 4.11
    new: 3.96

    10^7 digits of pi, threads = 8
    old: 2.128
    new: 1.438

    bernoulli(10^6), threads = 1
    old: 20.602
    new: 20.229

    bernoulli(10^6), threads = 8
    old: 5.51
    new: 4.77

Note that only arb_mul and friends are affected; computing pi also involves a final big division and square root which are still serial GMP operations, and all fmpz functions (for CRT in Bernoulli etc) remain serial.

**Comment by albinahlback** [comment]
> I'm thinking if we switch over functions like fmpz_mul and fmpz_addmul we might want to try inlining the 1-2 limb cases in those functions anywyay.

:partying_face:

**Comment by fredrik-johansson** [comment]
I just knew you'd say that!

**Comment by albinahlback** [comment]
My favorite catchphrase!
