### ISSUE TITLE
Unnecessary inclusions of headers

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1127]
Touching on #1070, we often include some unnecessary headers. In my opinion, we shouldn't bloat the headers with stuff that might be handy in some situations.

These are the headers in `flint.h` that I do not think should be loaded.

- One example of this is, as mentioned by Fredrik in #1070 (and one of the things I tried to fix in #1102) is the inclusion of `mpfr.h`, even though very few functions utilize MPFR (furthermore, I presume that only a minority of users utilize these functions).

- `stdio.h`, in my opinion, shouldn't be shipped with FLINT; Users should use `flint_printf` which does not require `stdio.h` externally (other stuff that actually requires `stdio.h` should use clauses, requiring `stdio.h` to be loaded, just like in GMP).

- `alloca` should be handled as in GMP, hence no `alloca.h` *by default*.

- `stdlib.h` does not need to be loaded, at all (see https://github.com/lattera/freebsd/blob/master/include/stdlib.h#L236 for justification in relation to previous point).

- `limits.h` is only needed for `ULONG_MAX` etc. But we already know the size of `mp_limb_t` and `mp_limb_signed_t`, so we won't need it.

- In relation to the point about `alloca`, `sys/param.h` does not need to be loaded.

**Comment by isuruf** [comment]
Slightly off-topic. Have you tried precompiled headers? Does that help?

**Comment by albinahlback** [comment]
No, I haven't. Per https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html, one can only use one precompiled header per compilation process and as we have a lot of headers I don't think this is possible.

**Comment by albinahlback** [comment]
I think the inclusions are somewhat optimized.
