### ISSUE TITLE
Documentation: Write pointers like `type * variable`

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1155]
Most pointers in FLINT are written as `type * variable`, while they are sometimes written like `type *variable`. The second way of writing in `.rst`-files screws up highlighting as it is interpretted as italic text (at least on Vim).

(Or at least establish some convention for this.)

**Comment by tthsqe12** [comment]
Looks like a typo as you wrote `type * variable` twice. I hope we can agree that it should be `type* variable` and `type& variable`, etc.

**Comment by fredrik-johansson** [comment]
How do you propose writing `int *x, *y`?

**Comment by tthsqe12** [comment]
I don't think we are going to get any agreement on that kind of declaration. But, I think albin is just looking for something uniform for the documentation, which is reasonable. As long as it is consistent and either `T * x` or `T* x` and not `T *x`, I don't mind either way.

**Comment by albinahlback** [comment]
Let's write it like `T * x` then! :-)

Going to fix this after my remake of the makefile.
