### ISSUE TITLE
Tests fail massively on s390x architecture

### ISSUE THREAD

**Issue by txgk** [flintlib/flint#1184]
Hi. I'm upgrading flint package in the Alpine Linux repositories with [this recipe](https://gitlab.alpinelinux.org/alpine/aports/-/blob/4217defe1b99a891e20cb125efa516448281ee9a/testing/flint/APKBUILD). So far s390x architecture fail on testing according to the logs. Quite a lot of tests fail, so for now I plan to just disable flint support for this architecture. I understand that fixing all these problems (in case there's even a desire for s390x support) may take a while, so I don't count on immediate fixes, but I'm leaving this here just for the sake of informing.

Summary list of failed tests:
```
202 - fmpz-test-t-get_d (Subprocess aborted)
264 - fmpz-test-t-set_d_2exp (Subprocess aborted)
300 - fmpz_vec-test-t-get_d_vec_2exp (Subprocess aborted)
338 - fmpz_poly-test-t-CLD_bound (Subprocess aborted)
383 - fmpz_poly-test-t-evaluate_horner_d_2exp (Subprocess aborted)
712 - fmpz_lll-test-t-heuristic_dot (Subprocess aborted)
713 - fmpz_lll-test-t-lll (Subprocess aborted)
714 - fmpz_lll-test-t-lll_d (Subprocess aborted)
715 - fmpz_lll-test-t-lll_d_heuristic (Subprocess aborted)
716 - fmpz_lll-test-t-lll_d_heuristic_with_removal (Subprocess aborted)
717 - fmpz_lll-test-t-lll_d_with_removal (Subprocess aborted)
718 - fmpz_lll-test-t-lll_d_with_removal_knapsack (Subprocess aborted)
721 - fmpz_lll-test-t-lll_with_removal (NUMERICAL)
722 - fmpz_lll-test-t-wrapper (Subprocess aborted)
723 - fmpz_lll-test-t-wrapper_with_removal (NUMERICAL)
724 - fmpz_lll-test-t-wrapper_with_removal_knapsack (NUMERICAL)
1306 - fmpz_poly_factor-test-t-factor (NUMERICAL)
2178 - fmpz_mpoly_factor-test-t-factor (NUMERICAL)
2182 - fmpz_mpoly_factor-test-t-factor_zassenhaus (NUMERICAL)
2191 - fmpq_mpoly_factor-test-t-factor (NUMERICAL)
```
[flint-build-log-s390x.txt](https://github.com/wbhart/flint2/files/9843041/flint-build-log-s390x.txt)

**Comment by albinahlback** [comment]
Have you tried using `make` instead of `cmake`? I don't think our CMake implementation is as good as our Makefile.

**Comment by albinahlback** [comment]
I don't see an immediate reason to why this would fail. I will close this due to a lack of further information and due to our lack of tests for non-x86 architectures. I don't think it should fail, however.

Feel free to open in case the problem prevails.
