### ISSUE TITLE
Configure failure on macOS: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by barracuda156** [flintlib/flint#1188]
```
-- Found Threads: TRUE  
<string>:4: Warning: 'with' will become a reserved keyword in Python 2.6
  File "<string>", line 4
    with open(join('/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_flint/flint/work/flint-2.9.0','qadic', 'CPimport.txt')) as fin:
            ^
SyntaxError: invalid syntax
CMake Error: File /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_math_flint/flint/work/build/CPimport.h.in does not exist.
CMake Error at CMakeLists.txt:127 (configure_file):
  configure_file Problem configuring file
```
Both 10.5 and 10.6 fail in this manner, with system gcc-4.2 and new gcc-12 alike.
https://trac.macports.org/ticket/66004

**Comment by fingolfin** [comment]
Well, that code is using the `with` which the error says : will become a reserved keyword in Python 2.6" -- i.e., it was written for Python 2.6 or newer (or more likely 2.7 or newer). Get a newer Python?

**Comment by albinahlback** [comment]
Wasn't Python 2.6 already old at the point this issue was open? I will close as this seems stale. Please reopen if it still persists.

**Comment by barracuda156** [comment]
Sorry, I should have updated and closed the issue earlier. It has been fixed in Macports in https://github.com/macports/macports-ports/commit/e8ea8e8460a60688929f5f2ab931e48fa75108cb
