### ISSUE TITLE
"This file is part of *not FLINT*"

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1230]
With MegaFLINT, the newly merged files contain a copyright claimer that says that the file does not belong to FLINT. For example, `calcium.h` of course contain the claimer
```
/*
    Copyright (C) 2020 Fredrik Johansson

    This file is part of Calcium.

    Calcium is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.  See <http://www.gnu.org/licenses/>.
*/
```
I suppose this should be changed. Should be easy to do with `sed` or `awk`.

**Comment by fredrik-johansson** [comment]
The LGPL does say:
> 1. You may copy and distribute verbatim copies of the Library's complete source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice and disclaimer of warranty; keep intact all the notices that refer to this License and to the absence of any warranty; and distribute a copy of this License along with the Library. 

I'm not sure if changing the library name in the notice would violate the prevision to "keep intact all the notices that refer to this License".

In (at least some) cases where we imported substantial code from (license-compatible!) versions of GMP or MPFR, we did keep original copyright notices; see for example the notice for mpn_get_d in gmpcompat.h and the notice in longlong.h

Hypothetically, some contributor to Arb could object to having the notice changed, though I doubt it.

Let's wait a bit and see if anyone else comments before doing the ``sed`` job.
