### ISSUE TITLE
Test various configurations on CI

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#1241]
+ We should check with BLAS enabled on at least one platform.
+ We should test non-x86_64 architectures: at least x86_32, arm32 and arm64

**Comment by albinahlback** [comment]
BLAS now has a check.

It would be nice to test ARM64, but currently this is only available through slow emulations. We could do this only on pushes to trunk.

**Comment by albinahlback** [comment]
I think we have a good enough platform check. The only parts of FLINT that are architecture dependent are `longlong.h` and `fft_small.h`. Here `longlong.h` is checked under `src/test`, and this along with `fft_small` are tested whenever something changes here.

Personally, I think we can skip the ARM32 tests as they would rely on emulation. Will close this, but feel free to open if you think it is still relevant.
