### ISSUE TITLE
Rename `trunk` to `main`

### ISSUE THREAD

**Issue by fingolfin** [flintlib/flint#1271]
The main development branch for Flint is named `trunk` which is extremely unusual for git repositories (it reminds me of SVN, maybe Flint used to use Subversion and was imported to git from there?).

Since Flint is undergoing some major changes right now, how about rectifying this and renaming the branch to `main`? That would of course require existing users to rename the branches locally, but that's not hard (at worst make a fresh clone), but it would lower the barrier for contributions for new people (admittedly only a little bit, but with these things, many minor nuisances can add up).

Note that GitHub has a feature for renaming the (primary) branch which should be used to do that, to ensure that e.g. open pull requests are correctly re-targeted.

**Comment by fredrik-johansson** [comment]
The main branch used to be ``master`` way back in the Paleozoic era (2009). At some point there was a technical problem with the git repository which messed up the ``master`` branch, and we figured that the easiest solution was to move to a clean new branch, which was named ``trunk``.

I'd be happy with renaming it to ``main``.

**Comment by albinahlback** [comment]
Fredrik just fixed this! Woho!
