### ISSUE TITLE
Not funrolling loops

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#1284]
Compiling with ``-funroll-loops`` massively bloats the library while improving performance for very few functions.

Compare the time to ``make -j``:

    with -funroll-loops:
    real	1m0,645s
    user	13m50,772s
    sys	1m29,875s

    without -funroll-loops:
    real	0m50,305s            (20% faster)
    user	11m10,914s
    sys	1m25,659s

The built library size:

    with -funroll-loops:
    -rwxrwxr-x   1 fredrik fredrik 67746968 mars  19 10:36 libflint.so.17.0.0

    without -funroll-loops:
    -rwxrwxr-x   1 fredrik fredrik 54396280 mars  19 10:37 libflint.so.17.0.0   (20% smaller)

How big is the performance impact? A first data point is to try running the tests for each module (``make check MOD=mod``, after building the tests):

                                funrolled    without  relative time
             thread_pool         0.330        0.326    (0.989x)
          thread_support         0.364        0.349    (0.959x)
            ulong_extras         3.921        3.950    (1.007x)
             long_extras         0.364        0.360    (0.988x)
                    perm         0.347        0.340    (0.979x)
           double_extras         0.330        0.319    (0.967x)
                   d_vec         0.462        0.456    (0.988x)
                   d_mat         0.342        0.329    (0.963x)
              mpn_extras         1.426        1.408    (0.987x)
                 mpf_vec         0.657        0.655    (0.996x)
                 mpf_mat         0.352        0.347    (0.985x)
                mpfr_vec         0.348        0.347    (0.997x)
                mpfr_mat         0.344        0.339    (0.984x)
                    nmod         0.318        0.307    (0.966x)
                nmod_vec         0.399        0.387    (0.969x)
                nmod_mat         2.559        2.649    (1.035x)
               nmod_poly         3.543        3.590    (1.013x)
                    fmpz         2.888        2.895    (1.003x)
                fmpz_vec         0.708        0.706    (0.996x)
                fmpz_mat         4.295        4.323    (1.007x)
               fmpz_poly         5.854        5.815    (0.993x)
                fmpz_mod         0.571        0.567    (0.994x)
            fmpz_mod_vec         0.319        0.313    (0.981x)
            fmpz_mod_mat         2.160        2.184    (1.011x)
           fmpz_mod_poly         2.259        2.266    (1.003x)
                    fmpq         3.354        3.344    (0.997x)
                fmpq_vec         0.405        0.396    (0.977x)
                fmpq_mat         2.583        2.566    (0.993x)
               fmpq_poly         2.884        2.856    (0.990x)
                      fq         0.527        0.514    (0.975x)
                  fq_vec         0.318        0.317    (0.996x)
                  fq_mat         0.787        0.792    (1.007x)
                 fq_poly         2.834        2.792    (0.985x)
                 fq_nmod         0.469        0.471    (1.005x)
             fq_nmod_vec         0.325        0.314    (0.967x)
             fq_nmod_mat         0.712        0.698    (0.981x)
            fq_nmod_poly         2.118        2.062    (0.974x)
                 fq_zech         0.801        0.792    (0.988x)
             fq_zech_vec         0.334        0.330    (0.988x)
             fq_zech_mat         0.781        0.756    (0.968x)
            fq_zech_poly         2.834        2.737    (0.966x)
              fq_default         0.380        0.373    (0.981x)
          fq_default_mat         0.333        0.332    (0.998x)
         fq_default_poly         0.338        0.327    (0.967x)
                fq_embed         0.406        0.409    (1.007x)
           fq_nmod_embed         0.345        0.347    (1.006x)
           fq_zech_embed         0.357        0.343    (0.960x)
                   padic         0.978        0.971    (0.992x)
               padic_mat         0.878        0.866    (0.986x)
              padic_poly         1.359        1.348    (0.992x)
                   qadic         0.555        0.555    (1.000x)
        nmod_poly_factor         1.165        1.163    (0.998x)
             fmpz_factor         7.074        7.068    (0.999x)
        fmpz_poly_factor         0.707        0.681    (0.963x)
    fmpz_mod_poly_factor         0.986        0.993    (1.008x)
          fq_poly_factor         1.616        1.607    (0.995x)
     fq_nmod_poly_factor         1.231        1.193    (0.969x)
     fq_zech_poly_factor         0.408        0.402    (0.985x)
    fq_default_poly_factor       0.565        0.548    (0.969x)
           nmod_poly_mat         0.895        0.894    (0.999x)
           fmpz_poly_mat         2.399        2.386    (0.994x)
                   mpoly         0.530        0.520    (0.981x)
              nmod_mpoly         5.436        5.396    (0.993x)
              fmpz_mpoly         8.251        8.300    (1.006x)
          fmpz_mod_mpoly         5.373        5.355    (0.997x)
              fmpq_mpoly         3.942        3.917    (0.994x)
           fq_nmod_mpoly         5.878        5.773    (0.982x)
           fq_zech_mpoly         0.320        0.308    (0.964x)
       nmod_mpoly_factor         1.081        1.063    (0.984x)
       fmpz_mpoly_factor         2.982        2.933    (0.983x)
    fmpz_mod_mpoly_factor        3.884        3.901    (1.004x)
       fmpq_mpoly_factor         0.351        0.346    (0.985x)
    fq_nmod_mpoly_factor         0.858        0.832    (0.970x)
    fq_zech_mpoly_factor         0.322        0.316    (0.980x)
                     fft        44.225       44.194    (0.999x)
             fmpz_poly_q         0.370        0.359    (0.969x)
                fmpz_lll         1.226        1.201    (0.980x)
                  n_poly         1.135        1.100    (0.969x)
                   arith         4.229        4.305    (1.018x)
                  qsieve         0.950        0.948    (0.998x)
                   aprcl         4.453        4.461    (1.002x)
                      nf         0.471        0.451    (0.958x)
                 nf_elem         1.183        1.160    (0.980x)
                     qfb         5.040        4.964    (0.985x)
         double_interval         0.413        0.404    (0.979x)
                    dlog         2.157        2.131    (0.988x)
             fmpz_extras         0.344        0.336    (0.977x)
                   fmpzi         0.456        0.461    (1.011x)
                bool_mat         0.365        0.367    (1.005x)
              partitions         0.818        0.811    (0.992x)
                     mag         0.798        0.791    (0.991x)
                     arf         2.772        2.735    (0.987x)
                     acf         0.321        0.320    (0.996x)
                     arb         7.307        7.207    (0.986x)
                     acb         3.532        3.425    (0.970x)
                 arb_mat         3.496        3.440    (0.984x)
                arb_poly         3.096        3.022    (0.976x)
                arb_calc         0.336        0.328    (0.975x)
             arb_hypgeom         2.499        2.464    (0.986x)
                 acb_mat         2.741        2.696    (0.984x)
                acb_poly         3.663        3.549    (0.969x)
                acb_calc         0.553        0.544    (0.985x)
             acb_hypgeom         5.981        5.869    (0.981x)
           arb_fmpz_poly         1.052        1.038    (0.987x)
              arb_fpwrap         0.330        0.334    (1.013x)
                 acb_dft         1.043        1.029    (0.986x)
            acb_elliptic         2.675        2.663    (0.995x)
             acb_modular         1.563        1.536    (0.983x)
           acb_dirichlet        11.936       11.717    (0.982x)
               dirichlet         1.685        1.649    (0.979x)
               bernoulli         1.824        1.802    (0.988x)
                 hypgeom         0.317        0.315    (0.994x)
                      gr        16.307       16.000    (0.981x)
                  gr_vec         0.573        0.567    (0.990x)
                  gr_mat         3.319        3.233    (0.974x)
                 gr_poly         4.096        3.975    (0.970x)
                gr_mpoly         2.468        2.455    (0.995x)
              gr_special         0.404        0.397    (0.983x)
                 calcium         0.316        0.310    (0.980x)
             utils_flint         0.340        0.333    (0.980x)
            fmpz_mpoly_q         0.540        0.530    (0.981x)
                   fexpr         0.354        0.337    (0.951x)
           fexpr_builtin         0.316        0.308    (0.975x)
                   qqbar         3.679        3.637    (0.989x)
                      ca        11.469       11.448    (0.998x)
                  ca_ext         0.331        0.320    (0.968x)
                ca_field         0.360        0.352    (0.977x)
                  ca_vec         0.312        0.310    (0.992x)
                 ca_poly         1.119        1.086    (0.970x)
                  ca_mat         1.532        1.495    (0.976x)

If anything, there is a small *speedup* for most modules, which is likely due to the code size reduction combined with the fact that the test suite starts many short-lived programs. This could be a useful improvement in itself, but of course we also care about long-running computations.

It looks like there is some slowdown in ``nmod_mat`` and ``nmod_poly`` and in some modules that depend on them. This is plausible as tight ``nmod`` loops seem like the most likely to benefit from loop unrolling. It would be good to do more detailed profiling to determine which if any functions are affected. We could then hopefully disable ``-funroll-loops`` globally and switch it on only for select files where it is known to have a positive impact.

**Comment by albinahlback** [comment]
Don't know if this makes sense in this conversation, but I would like to share what I have learned during the last year.

I have found that on GCC at least, unrolling of loops gives you the most performance and the "simplest" assembly output (that is, no "unnecessary" operations) when the function inputs are as simple as possible; that is, the function does not have to convert the inputs in the function (such as dereferencing the input, such as `int n = myinputarg->n`) and things like lengths are large and lengths are a multiple of some power of 2.

With this being said, a function like this:
```c
void myfunc(mystruct * arg, int n)
{
    int ix;

    for (ix = 0; ix < n; ix++)
        /* do something */
}
```
could be converted into
```c
/* Very important to not have this function inlined! */
__attribute__((noinline)) static void _myfunc(int * ptr1, int * ptr2, int n)
{
    int ix;

    if (n < 32 || n % 32 != 0)
        __builtin_unreachable();

    for (ix = 0; ix < n; ix++)
        /* do something */
}

void myfunc(mystruct * arg, int n)
{
    int ix;

    if (/* input is nice */)
    {
        _myfunc(arg->ptr1, arg->ptr2, n); /* and perhaps use smaller loop below if n % 32 != 0, but n is large */
        return;
    }

    for (ix = 0; ix < n; ix++)
        /* do something */
}
```

**Comment by fredrik-johansson** [comment]
Sample ``callgrind`` profile for ``build/nmod_mat/test/t-mul``. With funrolled loops:

```
5,168,932,565 (36.67%)  src/nmod_mat/test/t-mul.c:nmod_mat_mul_check [/home/fredrik/src/flint2/build/nmod_mat/test/t-mul]
3,185,678,149 (22.60%)  src/nmod_vec/dot.c:_nmod_vec_dot [/home/fredrik/src/flint2/libflint.so.17.0.0]
1,204,980,063 ( 8.55%)  src/nmod_vec/dot_ptr.c:_nmod_vec_dot_ptr [/home/fredrik/src/flint2/libflint.so.17.0.0]
1,132,424,090 ( 8.03%)  src/ulong_extras/randlimb.c:n_randlimb [/home/fredrik/src/flint2/libflint.so.17.0.0]
  735,833,491 ( 5.22%)  src/ulong_extras/randint.c:n_randint [/home/fredrik/src/flint2/libflint.so.17.0.0]
  430,511,145 ( 3.05%)  ./string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:__memset_avx2_unaligned_erms [/usr/lib/x86_64-linux-gnu/libc.so.6]
  325,729,898 ( 2.31%)  src/nmod_mat/mul_classical.c:_nmod_mat_addmul_packed_op [/home/fredrik/src/flint2/libflint.so.17.0.0]
  316,912,763 ( 2.25%)  src/ulong_extras/randtest.c:n_randtest_bits [/home/fredrik/src/flint2/libflint.so.17.0.0]
  297,836,130 ( 2.11%)  src/nmod_mat/mul_classical.c:_nmod_mat_mul_classical_op [/home/fredrik/src/flint2/libflint.so.17.0.0]
  240,047,430 ( 1.70%)  src/nmod_mat/randfull.c:nmod_mat_randfull [/home/fredrik/src/flint2/libflint.so.17.0.0]
  216,829,706 ( 1.54%)  src/nmod_vec/randtest.c:_nmod_vec_randtest [/home/fredrik/src/flint2/libflint.so.17.0.0]
  216,217,717 ( 1.53%)  src/ulong_extras/randbits.c:n_randbits [/home/fredrik/src/flint2/libflint.so.17.0.0]
  161,774,875 ( 1.15%)  ???:0x0000000004985170 [???]
  133,905,677 ( 0.95%)  ???:0x0000000004980cb0 [???]
  124,871,391 ( 0.89%)  src/ulong_extras/randtest.c:n_randtest [/home/fredrik/src/flint2/libflint.so.17.0.0]
   55,450,006 ( 0.39%)  src/nmod_mat/equal.c:nmod_mat_equal [/home/fredrik/src/flint2/libflint.so.17.0.0]
   27,749,203 ( 0.20%)  ???:0x000000000497acd0 [???]
```

Without funrolled loops:
```
5,968,058,597 (37.28%)  src/nmod_mat/test/t-mul.c:nmod_mat_mul_check [/home/fredrik/src/flint5/flint2/build/nmod_mat/test/t-mul]
4,038,686,344 (25.23%)  src/nmod_vec/dot.c:_nmod_vec_dot [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
1,349,750,229 ( 8.43%)  src/nmod_vec/dot_ptr.c:_nmod_vec_dot_ptr [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
1,132,424,090 ( 7.07%)  src/ulong_extras/randlimb.c:n_randlimb [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  735,833,491 ( 4.60%)  src/ulong_extras/randint.c:n_randint [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  430,511,145 ( 2.69%)  ./string/../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:__memset_avx2_unaligned_erms [/usr/lib/x86_64-linux-gnu/libc.so.6]
  350,074,744 ( 2.19%)  src/nmod_mat/mul_classical.c:_nmod_mat_addmul_packed_op [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  324,375,041 ( 2.03%)  src/nmod_mat/mul_classical.c:_nmod_mat_mul_classical_op [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  316,912,763 ( 1.98%)  src/ulong_extras/randtest.c:n_randtest_bits [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  247,686,973 ( 1.55%)  src/nmod_vec/randtest.c:_nmod_vec_randtest [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  240,047,430 ( 1.50%)  src/nmod_mat/randfull.c:nmod_mat_randfull [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  216,217,717 ( 1.35%)  src/ulong_extras/randbits.c:n_randbits [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
  161,774,875 ( 1.01%)  ???:0x0000000004a1c170 [???]
  133,905,677 ( 0.84%)  ???:0x0000000004a17cb0 [???]
  124,871,391 ( 0.78%)  src/ulong_extras/randtest.c:n_randtest [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
   87,016,604 ( 0.54%)  src/nmod_mat/equal.c:nmod_mat_equal [/home/fredrik/src/flint5/flint2/libflint.so.17.0.0]
```

This shows a pretty clear benefit for ``nmod`` inner loops like dot products, so probably we'd want to at least keep this on for ``nmod`` modules.

**Comment by albinahlback** [comment]
Perhaps we should define our own macros that includes pragmas (see https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html) in our own header (which is only for internal usage)?

**Comment by fredrik-johansson** [comment]
I propose by default enabling ``-funroll-loops`` for the modules

    ulong_extras nmod nmod_vec nmod_poly nmod_mat arith

and disabling it for all other modules.

It would be ideal to do it on a file-by-file basis, but I'm not too keen on going through all files to determine which ones actually benefit.

**Comment by albinahlback** [comment]
Yeah, sounds good! I think it is good to set two different CFLAGS and have two different sets of `DIRS` in the makefile with two different rules, one for `-funroll-loops` and one without.
