### ISSUE TITLE
Redefinition of configure constants

### ISSUE THREAD

**Issue by AndreasEnge** [flintlib/flint#1390]
Hello,

trying to move CM to use the git version of FLINT, I get the following warnings:
In file included from /home/enge/local/flint-git/include/flint/flint.h:29,
                 from /home/enge/local/flint-git/include/flint/thread_pool.h:15,
                 from /home/enge/local/flint-git/include/flint/fmpz_mod_poly.h:22,
                 from cm-impl.h:41,
                 from get_version.c:23:
/home/enge/local/flint-git/include/flint/flint-config.h:145: warning: "PACKAGE_BUGREPORT" redefined
  145 | #define PACKAGE_BUGREPORT "https://github.com/flintlib/flint2/issues/"
      | 
In file included from cm-impl.h:27:
../config.h:70: note: this is the location of the previous definition
   70 | #define PACKAGE_BUGREPORT "andreas.enge@inria.fr"
(and so on for other PACKAGE_* preprocessor constants).

I think that flint-config.h should not be installed, but used only during the compilation of FLINT itself. If you need flint.h to depend on the results of configuration, you can always use a flint.h.in template.

Andreas

**Comment by fredrik-johansson** [comment]
Isn't the problem here that you have an old ``config.h`` lying around, which needs to be removed?

**Comment by AndreasEnge** [comment]
@albinahlback  These are ortogonal concerns, I think. In the first place, one should not install config.h; then if part of it is needed, one needs a mechanism to include only this part into flint.h. Or otherwise said, config.h should be treated as if it were named config-impl.h :-)

This is independent of how many header files there are, or whether one uses an additional flint-impl.h.

**Comment by fredrik-johansson** [comment]
I don't see any reason to hide ``FLINT_`` configure settings from users. A user might want to check for ``FLINT_HAVE_FFT_SMALL`` in their own code, for example.

But by all means, autotools-only boilerplate without the ``FLINT`` prefix could go in its own hidden config file or ``/dev/null`` or whatever.

**Comment by jengelh** [comment]
The boilerplate lands in the first file specified in `AC_CONFIG_HEADERS([ ... ])`, so... just specify more files like [config.h flint-public-config.h].
