### ISSUE TITLE
flintxx folder not installed when using cmake?

### ISSUE THREAD

**Issue by bjodah** [flintlib/flint#1405]
I was trying to build a 3rd party package which includes "flintxx/evaluation_tools.h", looks like I built and installed flint2 using cmake instead of the autotools scripts. Perhaps autotools is still the preferred method? (I didn't see the equivalent of --enable-cxx=yes among the options in the CMakeLists.txt)

EDIT: I think this is the relevant line in Makefile.in
https://github.com/flintlib/flint2/blob/17536724734a3a2a7edb8fd011336b3690dcebf7/Makefile.in#L762

I'm not very well versed in CMake, but I think something along these lines might work:
```CMake
file(GLOB FLINT_CXX_HEADERS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}/src/ flintxx/*.h)
file(GLOB FLINT_CXX_HEADERS_PUBLIC RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}/src/flintxx_public/ *xx.h)
target_sources(flint PUBLIC FILE_SET HEADERS
    BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/src
    FILES
    ${FLINT_CXX_HEADERS}
)
target_sources(flint PUBLIC FILE_SET HEADERS
    BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/src/flintxx_public
    FILES
    ${FLINT_CXX_HEADERS_PUBLIC}
)
```

**Comment by edgarcosta** [comment]
see https://github.com/flintlib/flintxx/issues/4
