### ISSUE TITLE
Sphinx errors when building documentation

### ISSUE THREAD

**Issue by dlesnoff** [flintlib/flint#1406]
I got the following output when typing `make html` in `doc` folder.
```python

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 326, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/dsk/l1/libraries/flint/doc/source/conf.py", line 32, in <module>
    for _line in open("../../configure.ac").readlines():
  File "/usr/lib/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 229: ordinal not in range(128)

make: *** [Makefile:20: coverage] Error 2
```
Is my python/sphinx version too old?
```raw
python -VV
Python 3.8.16 (default, Jun 12 2023, 18:09:05) 
[GCC 11.2.0]
```
My python version appears different than the one used for building the documentation.

**Comment by havarddj** [comment]
I just tested this, seems to build fine.
```
> sphinx-build --version
sphinx-build 7.2.6
```

**Comment by dlesnoff** [comment]
Strange. I do not remember on which machine, nor when I ran `make html`. On my laptop, building html docs seems to be fine.
Running Sphinx v5.0.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 166 source files that are out of date
updating environment: [new config] 166 added, 0 changed, 0 removed
reading sources... [100%] utils_flint                                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] utils_flint                                                      
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in build/html.

I can not reproduce the issue. I close this until I stumble upon something similar. Thanks for asking.
