### ISSUE TITLE
fmpz_poly_factor_squarefree crashes for the zero polynomial

### ISSUE THREAD

**Issue by fagu** [flintlib/flint#1414]
The following gives a segmentation fault:
```cpp
#include "flint/flint.h"
#include "flint/fmpz_poly.h"
#include "flint/fmpz_poly_factor.h"

int main() {
	fmpz_poly_t a;
	fmpz_poly_init(a);
	fmpz_poly_factor_t fac;
	fmpz_poly_factor_init(fac);
	fmpz_poly_factor_squarefree(fac, a);
	return 0;
}
```
The issue is probably this line. (The zero polynomial has no leading coefficient.)
https://github.com/flintlib/flint2/blob/ef89816abda221fc40cb4a960430cb570ef0f43c/src/fmpz_poly_factor/factor_squarefree.c#L20

**Comment by edgarcosta** [comment]
I will look into this
