### ISSUE TITLE
Issue regenerating certain files via `config.status`

### ISSUE THREAD

**Issue by fingolfin** [flintlib/flint#1526]
The `config.status` script is generated by `configure` and among other things is meant to allow regenerating files. For example:
```
$ ./config.status Makefile
config.status: creating Makefile
$
```
However this is broken for some files in the sense that "regenerating" them just hangs. E.g.:
```
$ ./config.status src/fmpz/fmpz.c
config.status: creating src/fmpz/fmpz.c
[... and now it hangs there forever ...]
```

Affected: `src/fmpz/fmpz.c`, `src/fft_tuning.h`

Not affected: `Makefile`, `flint.pc`, `src/config.h`

This may be a bug in autoconf, or the FLINT build system, or something else. I reproduced it on macOS (with autoconf 2.71) and Gentoo (with autoconf 2.71). I'll try if I can reproduce it with 2.69 later.

**Comment by albinahlback** [comment]
`gmpcompat.h` is also affected now. I'm trying to look into it.

**Comment by albinahlback** [comment]
The problem, as I'm sure Max figured out, is that when writing
```autoconf
if test "$some_condition" = "yes";
then
    fmpz_c="src/fmpz/link/fmpz_reentrant.c"
else
    fmpz_c="src/fmpz/link/fmpz_single.c"
fi
AC_CONFIG_FILES([src/fmpz/fmpz.c:${fmpz_c}])
```
the configuration process works as intended, but `config.status` miss the definition of `fmpz_c`, so when `config.status` process the following lines in its file
```bash
# Handling of arguments.
for ac_config_target in $ac_config_targets
do
  case $ac_config_target in
    "libtool") CONFIG_COMMANDS="$CONFIG_COMMANDS libtool" ;;
    "src/config.h") CONFIG_HEADERS="$CONFIG_HEADERS src/config.h" ;;
    "src/flint-config.h") CONFIG_HEADERS="$CONFIG_HEADERS src/flint-config.h" ;;
    "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
    "flint.pc") CONFIG_FILES="$CONFIG_FILES flint.pc" ;;
    "src/flint.h") CONFIG_FILES="$CONFIG_FILES src/flint.h" ;;
    "src/gmpcompat.h") CONFIG_FILES="$CONFIG_FILES src/gmpcompat.h:src/${gmpcompat_h_in}" ;;
    "src/fmpz/fmpz.c") CONFIG_FILES="$CONFIG_FILES src/fmpz/fmpz.c:"${fmpz_c}"" ;;
    "src/fft_tuning.h") CONFIG_FILES="$CONFIG_FILES src/fft_tuning.h:${fft_tuning_in}" ;;

  *) as_fn_error $? "invalid argument: \`$ac_config_target'" "$LINENO" 5;;
  esac
done
```
it will miss the definition of `fmpz_c`, so it will never be able to complete the action.

I have tried to search for solutions, but I cannot seem to find any. And I cannot figure out a nice "fixup" with `AC_CONFIG_COMMANDS_POST` for example.

**Comment by fingolfin** [comment]
Thanks @albinahlback , no I was not aware / totally missed it -- but thanks to your discovery I think I now know how to fix it :-). I'll give it a try.
