### ISSUE TITLE
cmake build broken in 3.0.0

### ISSUE THREAD

**Issue by antonio-rojas** [flintlib/flint#1543]
```
CMake Error at CMakeLists.txt:259 (add_library):
  Cannot find source file:

    src/interfaces/NTL-interface.cpp
```

`NTL-interface.cpp` was removed in 14bceec34145a20e767b41ccc24bb4a40cfa957d

**Comment by antonio-rojas** [comment]
Seems the `WITH_NTL` option no longer does anything besides breaking the build, and should be removed.

**Comment by edgarcosta** [comment]
> At the moment the --with-ntl configure option and its variants are
still there, but are only used to decide whether
interfaces/test/t-NTL-interface.cpp should be compiled and where to
look for NTL for doing that. Afaict the tests in question still pass.

as mentioned in #1489

**Comment by fredrik-johansson** [comment]
@antonio-rojas Can you verify that this is solved now?

**Comment by antonio-rojas** [comment]
On git master configure fails right away 
```
CMake Error at CMakeLists.txt:26 (project):
  VERSION "3.1.0-dev" format invalid.


-- Configuring incomplete, errors occurred!
```

**Comment by fredrik-johansson** [comment]
Indeed, this seems to work on the 3.0 branch but not on trunk with the ``-dev`` suffix.

**Comment by antonio-rojas** [comment]
oh, I wasn't aware of the 3.0 branch. The NTL issue is fixed there indeed.
