### ISSUE TITLE
malformed version macros in cmake build

### ISSUE THREAD

**Issue by antonio-rojas** [flintlib/flint#1544]
The cmake build produces a malformed `flint.h` with undefined version macros. The variables in `flint.h.in` are named FLINT_FOO, while in CMakeLists.txt they are named FLINT_FOO_SO.

**Comment by fredrik-johansson** [comment]
@antonio-rojas Can you verify that this is solved now?

**Comment by antonio-rojas** [comment]
It's solved in the 3.0 branch
