### ISSUE TITLE
Add pkg-config to cmake build

### ISSUE THREAD

**Issue by Gbury** [flintlib/flint#1554]
pkg-config files for `flint` were added in #1299 but only for the autoconf/makefile build from what I can tell.
How hard would it be to make it so that the cmake build also generates and installs the pkg-config file ?

**Comment by albinahlback** [comment]
As of the current state of FLINT, we only utilize CMake to enable compiling FLINT natively on Windows. Hence, we focus on Autotools and CMake will lag behind in some features. We have now documented this (we did this a couple of weeks ago), and now warn the user when user is compiling with CMake on non-Windows machines.

Thus, adding pkg-config to CMake is not on our list, but you are very welcome to open a PR.
