### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by CryptoMeena** [flintlib/flint#1557]
I am getting the following errors while running the ./configure command. I have added the include directories of C. But still not able to find the stdarg.h file
./configure   --includedir=/usr/lib/gcc/x86_64-linux-gnu/11/include

checking stdarg.h presence... yes
configure: WARNING: stdarg.h: present but cannot be compiled
configure: WARNING: stdarg.h:     check for missing prerequisite headers?
configure: WARNING: stdarg.h: see the Autoconf documentation
configure: WARNING: stdarg.h:     section "Present But Cannot Be Compiled"
configure: WARNING: stdarg.h: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------------------------------- ##
configure: WARNING:     ## Report this to https://github.com/flintlib/flint/issues/ ##
configure: WARNING:     ## -------------------------------------------------------- ##
checking for stdarg.h... no
configure: error: Could not find a mandatory header!

**Comment by albinahlback** [comment]
`--includedir` is for fine-tuning the installation path, not the actual include path.

**Comment by albinahlback** [comment]
Let me know if this issue persists, but if you put in `CC=gcc`, it should have `/usr/lib/gcc/x86_64-linux-gnu/11/include` as an include directory.

If this does not work, you can solve this by either modify some environmental variable (I think they are something like `INCLUDE_PATH`, `LD_INCLUDE_PATH` or `C_INCLUDE_PATH`), or setting the `CPPFLAGS` to `-I/usr/lib/gcc/x86_64-linux-gnu/11/include`.

**Comment by albinahlback** [comment]
Feel free to reopen.
