### ISSUE TITLE
Remove version numbers for Antic, Arb and Calcium

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1560]
More precisely I mean `__XXX_VERSION`, `__XXX_VERSION_MINOR`, `__XXX_VERSION_PATCHLEVEL`, `XXX_VERSION` and `__XXX_RELEASE`. Is this reasonable, or are they still necessary for backward compatibility?

**Comment by albinahlback** [comment]
Will just mention that the patchlevel does not match the version string for Calcium.

**Comment by fredrik-johansson** [comment]
Maybe we can mark them as deprecated in 3.1 for compatibility and remove them in 3.2?

**Comment by albinahlback** [comment]
Sounds like a good idea!
