### ISSUE TITLE
gr_is_integer shown in document, but missing in actual code.

### ISSUE THREAD

**Issue by F-Feng** [flintlib/flint#1561]
The function `gr_is_integer` appears in the document, but it seems that the corresponding function cannot be found in the actual code.

By the way, I was wondering if there are any plans to introduce a class like `gr_poly_q_t` in the future. Currently, I am using `fmpz_poly_q_t`, but I am considering transitioning to the `gr_` interface. Therefore, I am curious if it would be worthwhile to introduce such a function.

Thanks very much!

**Comment by fredrik-johansson** [comment]
> The function gr_is_integer appears in the document, but it seems that the corresponding function cannot be found in the actual code.

Yes, there are a few such functions which have not yet been implemented.

> By the way, I was wondering if there are any plans to introduce a class like gr_poly_q_t in the future. Currently, I am using fmpz_poly_q_t, but I am considering transitioning to the gr_ interface. Therefore, I am curious if it would be worthwhile to introduce such a function.

We should definitely have something like this, but I'm not sure if we'll do an ``gr_poly_q`` type, fully generic fraction fields, or both. We could conceivably have fully generic fraction field code and make ``fmpz_poly_q``, ``fmpz_mpoly_q`` and ``gr_poly_q`` simple wrappers around that.

**Comment by F-Feng** [comment]
Thanks very much for the information, and I am eagerly anticipating the inclusion of these features.
