### ISSUE TITLE
Implement a precomputed inverse type for fmpz_mod_poly

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#158]
Currently we simply supply the modulus n to all the functions in fmpz_mod_poly. It really should take a mod structure, the same as the nmod_poly module. This would allow us to later on supply precomputed inverses and the like.

**Comment by fredrik-johansson** [comment]
The contexts have been implemented but most underscore functions still take the modulus rather than a context object as input.

**Comment by fredrik-johansson** [comment]
This was fixed recently.
