### ISSUE TITLE
flintxx codegen test fails with gcc 4.8.2

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#163]
We have the following fail:

codegen....FAIL
test/t-codegen.cpp:755: assertion stripaddr(ass1) == stripaddr(ass2) failed
SKIP (did not expect pass anyway)

**Comment by albinahlback** [comment]
Is this still relevant? I think five-year support of GCC is somewhat reasonable, and since 4.* is more than seven years old, I think we should close this issue. (However, I think that it's another issue if it is still happens on newer GCC.)

**Comment by wbhart** [comment]
I don't know if the issue still occurs or not. I won't close until we know. 4.8.2 is admittedly old.

I'm not sure what they are using on supercomputers, but it probably has a very large patch number, so probably not this.

**Comment by albinahlback** [comment]
Regarding supercomputers:

[This one in USA](https://www.osc.edu/resources/available_software/software_list/gnu_compilers) says 9.1.0.

[This one in Linköping](https://www.nsc.liu.se/software/compilers/gcc/) suggests 4.8.2. However, if one looks at its source code, it might be the case that the site was written in 2015. More specifically, if one looks at [the linked page](https://www.nsc.liu.se/software/math-libraries/) (under the assumption that it was written at the same time period), it suggests that it was written in 2013 (same release year as 4.8.2). As this is the main computing center in Sweden, it would really surprise me if this is the most recent version available there.

[This one in USA](https://docs.olcf.ornl.gov/software/software-news.html?highlight=gcc) says that at 11.1.0 is available. This website also seems to be the most recently updated (this particular one was updated in August 2021).

Thus, I think it's safe to assume that every supercomputer has a GCC version available that is at most three year old.

**Comment by wbhart** [comment]
I find many different versions in use, 4.8.x, 4.9.x, e.g.

http://www.serc.iisc.ac.in/gnu-compiler-collection-delta/

This issue will have to be fixed.

**Comment by albinahlback** [comment]
That seems to be have been written in 2015.
