### ISSUE TITLE
Cannot build the trunk branch

### ISSUE THREAD

**Issue by Sander80** [flintlib/flint#1659]
After https://github.com/flintlib/flint/issues/1652 was fixed, I tried to build the trunk branch and failed again (now commit 3ef82531, but earlier saw the same thing)

```
  CC  fmpz_mpoly/divrem_array.lo
  CC  fmpz_mpoly/div_monagan_pearce.lo
  CC  fmpz_mpoly/divides_monagan_pearce.lo
  CC  fmpz_mpoly/divides_heap_threaded.lo
  CC  fmpz_mpoly/divides.lo
make[1]: *** No rule to make target 'src/hashmap.h', needed by 'build/fmpz_mpoly/divides_array.lo'.  Stop.
make[1]: Leaving directory '/users/guest/asmirnov/fire.public/FIRE6/extra/fuel/extra/flint2'
make: *** [Makefile:63: flintLibrary] Error 2
```

Tried a few times, both with -j and not, fails at this particular place.

Is any specific information on the computer needed?

**Comment by fredrik-johansson** [comment]
There are probably some old build files around. Did you run ``make clean``? If that isn't enough, you may have to re-run ``configure`` (if that still doesn't work, maybe run ``bootstrap.sh`` to regenerate ``configure`` as well).
