### ISSUE TITLE
Improve nmod dot products

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#1661]
We should be doing something like this:

https://github.com/vneiger/pml/blob/master/flint-extras/nmod_vec_extra/src/nmod_vec_dot_small_modulus.c

https://github.com/vneiger/pml/blob/master/flint-extras/nmod_vec_extra/src/nmod_vec_integer_dot_product.c

**Comment by vneiger** [comment]
Just updated with the most recent (faster) version, and with correct author information. See also
https://github.com/vneiger/pml/blob/master/flint-extras/nmod_mat_extra/src/nmod_mat_mul_small_modulus.c
which, after only some preliminary testing/benchmarking, gives quite nice timings on my laptop for matrix multiplication over 30-bit nmods. The plan was indeed to bring this into flint sooner or later.
