### ISSUE TITLE
make profile does nothing

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#1672]
@albinahlback Is it just me or is ``make profile`` broken?

```
$ make profile MOD=ulong_extras
Makefile:467: Dependency tracking only set to cover the profile executables of ulong_extras.
make: Nothing to be done for 'profile'.

$ build/ulong_extras/profile/p-gcd
bash: build/ulong_extras/profile/p-gcd: No such file or directory

```

**Comment by albinahlback** [comment]
Yeah, sorry. I did this because of the unused `n_factor_pp1_table_insert` in `ulong_extras/factor_pp1.c`, which is now defined only if `--enable-profiling`. But I will remove the option and fix this, it is not a good solution now when I think of it.

**Comment by albinahlback** [comment]
It should be fixed now.

**Comment by fredrik-johansson** [comment]
Thanks!
