### ISSUE TITLE
fmpz_mod_poly division get undefined _fmpz_mod_poly_divrem_divconquer

### ISSUE THREAD

**Issue by KuraTheDog** [flintlib/flint#1680]
Previously been using "fmpz_mod_poly_rem", recently updated and now it stopped working.
Installed on Mac via brew, have version 3.0.1

Specifically, when trying to build I get e.g. 
```
ld: Undefined symbols:
  _fmpz_mod_poly_divrem_divconquer, referenced from:
      _main in test.cpp.o
```

Minimal failing example:
```
#include <flint/fmpz_mod_poly.h>
int main() {
    fmpz_t mod; fmpz_init_set_si(mod, 101);
    fmpz_mod_ctx_t ctx; fmpz_mod_ctx_init(ctx, mod);

    fmpz_mod_poly_t r; fmpz_mod_poly_init(r, ctx);
    fmpz_mod_poly_t a; fmpz_mod_poly_init(a, ctx);
    fmpz_mod_poly_t b; fmpz_mod_poly_init(b, ctx);

    fmpz_mod_poly_rem(r, a, b, ctx);

    return 0;
}
```

It runs if I comment out the "rem" line. 
It also works if I replace "rem" with e.g. "add", so it should be installed right. 

Looking at history, "_fmpz_mod_poly_divrem_divconquer" was removed in 3.0, but it seems like fmpz_mod_poly is still relying on it.

Also tried divrem and div, both also fail with the same error.

**Comment by albinahlback** [comment]
Neither in trunk, tag v3.0.1 or tag v3.0.0 I can find any references in the source code to `_fmpz_mod_poly_divrem_divconquer`. Looking at [the formula](https://formulae.brew.sh/api/formula/flint.json), it points to https://flintlib.org/flint-3.0.1.tar.gz which does not contain any references either.

**Comment by fredrik-johansson** [comment]
Probably you have an old version of ``fmpz_mod_poly.h`` somewhere on your machine which is being included.

**Comment by KuraTheDog** [comment]
Yeah, looking through the github, that seems to possibly be the case.
Cmake tells me it's using "/opt/homebrew/include", which seems to be the normal place, and fmpz_mod_poly.h there looks to be the right one (only divconquer is the #define on top). 
I'll hunt down more, and worst case reinstall.

**Comment by KuraTheDog** [comment]
So turns out I have both "/usr/local/Cellar/flint/2.9.0/include/flint/fmpz_mod_poly.h", and "/opt/homebrew/Cellar/flint/3.0.1/include/flint/fmpz_mod_poly.h", so it seems to be a brew problem. I'll go poke at filesystems. Thanks.

**Comment by KuraTheDog** [comment]
Resolving this fully: Turns out it was due to brew having a different location on M1 mac vs before, but it never caused conflict until now (due to restore from backup). Had to full delete/reinstall brew to get everything in the right folder and clear links to older versions
