### ISSUE TITLE
static library with -fPIC

### ISSUE THREAD

**Issue by apelloni** [flintlib/flint#1681]
I've compiled FLINT3.0.1 static library to be used with rust, on my computer running arch (Linux 6.6.6-arch1-1) I've no problems, but when compiling the same rust version on centos ( CentOS Linux 7 (Core), it requires the library to be compiled with `-fPIC`.
Both cases run with the same rust version but different gcc/libtool/autoconf/gmp/mpfr

| | gcc |autoconf |libtool | libgmp|libmpfr |
|--           |--            |--                   |--                |--              |--             |
|on arch:|13.2| 2.71| 2.4.7| 6.3.0| 4.2.1|
|on centos:| 10.1| 2.69| 2.4.2| 6.0.0| 3.1.1|

I've currently just modified the Makefile to add the missing flag.
Would it be possible to have an option in `./configure` to force compilation with `-fPIC` regardless of the library type?

Maybe it's already possible, but I couldn't find the way.

**Comment by albinahlback** [comment]
> I've compiled FLINT3.0.1 static library to be used with rust, on my computer running arch (Linux 6.6.6-arch1-1) I've no problems, but when compiling the same rust version on centos ( CentOS Linux 7 (Core), it requires the library to be compiled with `-fPIC`.

So when you try to compile a static library of FLINT on CentOS, it compiles it with `-fPIC`? If this indeed is the case, could you send the generated `config.log`? We do not want `-fPIC` to be added to CFLAGS for static libraries.

> I've currently just modified the Makefile to add the missing flag. Would it be possible to have an option in `./configure` to force compilation with `-fPIC` regardless of the library type?

This seems contradictory of the last statement. Do you really want `-fPIC` with a static library?

To answer your question, you can just specify what CFLAGS you want to use via `./configure CFLAGS="-foption1 -moption2..."`.

**Comment by albinahlback** [comment]
Please let me know if my answer didn't give you a solution. Closing for now.
