### ISSUE TITLE
Building CMake vs Autotools

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1692]
After converting the configure script to autoconf, the configuration process using autoconf has become somewhat complete. However, this is not really the case for CMake, which is functional but, in my opinion, not as "refined" as the autoconf script.

I think it is a good idea if we document why we have CMake along side with autoconf, and what benefits and drawbacks this has compared to autoconf.

What I can think of is the following (in a functional sense):

### Drawbacks of CMake
- No helpstrings(?)
- ~Cannot set variables such as compiler, cflags, etc.(?)~
- Cannot use GMP internals
- No upcoming support of assembly
- Some settings from autoconf are missing
- No fine tuning of variables such as debug mode without assert

### Benefits of CMake
- Can compile for Windows
- Can build out of tree (I think)

**Comment by albinahlback** [comment]
Fredrik and I seem to agree that CMake's only task here is to being able to compile for Windows. We should clarify to non-Windows users that Autotools is recommended.

**Comment by isuruf** [comment]
> No helpstrings

For the options? We can add them.

> Cannot set variables such as compiler, cflags, etc.(?)

Not sure what you mean here. We can set `CC, CFLAGS`, env variables etc.

**Comment by albinahlback** [comment]
> > Cannot set variables such as compiler, cflags, etc.(?)
> 
> Not sure what you mean here. We can set `CC, CFLAGS`, env variables etc.

My CMake knowledge is a bad, you are correct.
