### ISSUE TITLE
Strip library after building

### ISSUE THREAD

**Issue by albinahlback** [flintlib/flint#1701]
We should strip the library after building.

**Comment by fredrik-johansson** [comment]
What does this do? Are there any drawbacks?

**Comment by albinahlback** [comment]
Removes non-essential information from files (so I suppose we cannot do this when `--enable-debug`). This leads to a smaller file and possibly better performance. On my system with default flags with `--disable-debug` I get a reduction of about 7% in size of the binary library.

**Comment by edgarcosta** [comment]
We are talking about a couple of megabytes.
I don't see the gain in adding that unnecessary step to our build system.
I think if a (distributing) system is really focused on space, they can do that themselves.
