### ISSUE TITLE
Incorrect polynomial algebra at Redhat Linux

### ISSUE THREAD

**Issue by Sander80** [flintlib/flint#1709]
Greetings again.
I am trying to run out programs at a cluster and encountered an unexpected problem.
Here is a small program to demonstrate it

```
#include <iostream>
#include "flint/fmpz.h"
#include "flint/fmpz_mpoly.h"

int main(int argc, char** argv) {

    constexpr int nvars = 1;
    fmpz_mpoly_ctx_t ctx;
    fmpz_mpoly_ctx_init(ctx, nvars, ORD_LEX);
    char* var = (char*) "x";
    char* vars[1];
    vars[0] = var;

    fmpz_mpoly_t a, b, c, d, e;
    fmpz_mpoly_init(a, ctx);
    fmpz_mpoly_init(b, ctx);
    fmpz_mpoly_init(c, ctx);
    fmpz_mpoly_init(d, ctx);
    fmpz_mpoly_init(e, ctx);
    fmpz_mpoly_set_str_pretty(a, "-2", (const char**) vars, ctx); // set polynomial a = -2
    fmpz_mpoly_set_str_pretty(b, "1", (const char**) vars, ctx); // set polynomial b = 1
    fmpz_mpoly_mul(c, a, b, ctx); // set c = a * b
    fmpz_mpoly_gcd(d, a, b, ctx); // set d = gcd(a, b)
    fmpz_mpoly_div(e, a, b, ctx); // set e = a/b, assuming exact division

    char* a_string = fmpz_mpoly_get_str_pretty(a, (const char**) vars, ctx);
    char* b_string = fmpz_mpoly_get_str_pretty(b, (const char**) vars, ctx);
    char* c_string = fmpz_mpoly_get_str_pretty(c, (const char**) vars, ctx);
    char* d_string = fmpz_mpoly_get_str_pretty(d, (const char**) vars, ctx);
    char* e_string = fmpz_mpoly_get_str_pretty(e, (const char**) vars, ctx);
    std::cout << " a = " << a_string << std::endl;
    std::cout << " b = " << b_string << std::endl;
    std::cout << " a*b = " << c_string << std::endl;
    std::cout << " gcd(a,b) = " << d_string << std::endl;
    std::cout << " a/b = " << e_string << std::endl;
    free(a_string);
    free(b_string);
    free(c_string);
    free(d_string);
    free(e_string);

}
```

Here we multiply -2 by 1 and get...

```
 a = -2
 b = 1
 a*b = -79228162532711081658663567362
 gcd(a,b) = 1
 a/b = -13835058057429647362
```

Locally at Ubuntu everything works correctly.

What knowledge of the system could I provide?

```
[smirnov.a@polus-ib library]$ uname -a
Linux polus-ib.bmc.hpc.cs.msu.ru 3.10.0-693.1.1.el7.ppc64le #1 SMP Thu Aug 3 08:15:43 EDT 2017 ppc64le ppc64le ppc64le GNU/Linux
[smirnov.a@polus-ib library]$ cd ..^C
(reverse-i-search)`car': source "$HOME/.^Crgo/env"
[smirnov.a@polus-ib library]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
```

I had problems at this system, I think char is signed here by default. Do you think it might be the reason?

I can expriment with simpler code without polynomials if you wish.

**Comment by albinahlback** [comment]
As usual, what version of FLINT at you using on each system? If main branch on both, are they at the same stage?

**Comment by albinahlback** [comment]
You do not check return value when setting the polynomials. What is the return value?

**Comment by Sander80** [comment]
- Checked, the return valur iz 0
- Without that it fails to compile `test.cpp:30:51: error: invalid conversion from ‘char**’ to ‘const char**’ [-fpermissive]`
- Works on my machine too. On many machines. That was the first machine I encountered it
- it's commit be934d (after you fixed printing)

**Comment by albinahlback** [comment]
Hmm, so it is a PowerPC on Redhat? I know Dan (author of most of the multivariate polynomial code in FLINT) tricked some with endianness. I will see if I can figure out what is wrong.

**Comment by albinahlback** [comment]
Do you have `config.log` from the configuration process?

**Comment by Sander80** [comment]
I know the processors are IBP Power8, the system is Redhat Linux... I can give extra commands and provide output if needed. I will rebuild flint and attach soon

**Comment by Sander80** [comment]
[flint.log](https://github.com/flintlib/flint/files/13898456/flint.log)

**Comment by albinahlback** [comment]
Sorry, but after looking at the code and the log, I do not have an answer at the moment. I mean, it seems to interpret and print them correctly. It seems to be some arithmetic that's incorrect, or perhaps some incorrect representation (however, it is not big endian, so the problem doesn't lie here).

Perhaps @fredrik-johansson has an answer.

**Comment by fredrik-johansson** [comment]
``make check`` fails in pretty much every module on PowerPC, starting here:

    $ make check
    add_ssaaaa....PASS
    add_sssaaaaaa....FAIL:
    a[2] = 21701, a[1] = 32769, a[0] = 18446744073709551615
    b[2] = 859109819487, b[1] = 18446744073709551615, b[0] = 137438953472
    s[2] = 859109841188, s[1] = 32769, s[0] = 137438953471
    t[2] = 859109841189, t[1] = 32769, t[0] = 137438953471
    make: *** [Makefile:736: build/test/main_TEST_RUN] Aborted

**Comment by Sander80** [comment]
My wild guess is that this is since "char" is unsigned by default on these systems. In my code I had to specifically use "signed char" in some places. Might yoy rely on the signess of char somewhere?

**Comment by albinahlback** [comment]
> `make check` fails in pretty much every module on PowerPC, starting here:
> 
> ```
> $ make check
> add_ssaaaa....PASS
> add_sssaaaaaa....FAIL:
> a[2] = 21701, a[1] = 32769, a[0] = 18446744073709551615
> b[2] = 859109819487, b[1] = 18446744073709551615, b[0] = 137438953472
> s[2] = 859109841188, s[1] = 32769, s[0] = 137438953471
> t[2] = 859109841189, t[1] = 32769, t[0] = 137438953471
> make: *** [Makefile:736: build/test/main_TEST_RUN] Aborted
> ```

Hmm, do you know how long back this tracks? Is it perhaps since the new `longlong.h`, or is this from before? Weird that it fails for generics.

**Comment by Sander80** [comment]
If you wish, I can test the code on other commits on that machine. It takes time to rebuild, so bisecting will take long, so peehaps you suggest test commits

**Comment by fredrik-johansson** [comment]
Tests pass on the 3.0.1 branch. The longlong changes are a plausible culprit since the ``add_sssaaaaaa`` test fails and this doesn't depend on anything else.

**Comment by Sander80** [comment]
v3.0.1 on my test program is also fine.

Do you need me to rebuild something intermediate?

**Comment by albinahlback** [comment]
Sorry for the delay, but I will fix this today.

**Comment by albinahlback** [comment]
It should be fixed by now.

**Comment by Sander80** [comment]
I see it is, I will check it now

**Comment by Sander80** [comment]
Hmm cannot built it
```
  CC  fmpz_mpoly/is_fmpz.c
  CC  fmpz_mpoly/add.c
  CC  fmpz_mpoly/mul_monomial.c
  CC  fmpz_mpoly/gcd_cofactors.c
  CC  fmpz_mpoly/cmp.c
  CC  fmpz_mpoly/get_term_exp_ui.c
  CC  fmpz_mpoly/set_term_exp_fmpz.c
  CC  fmpz_mpoly/mul_dense.c
  CC  fmpz_mpoly/gcd.c
make[1]: *** Нет правила для сборки цели «src/hashmap.h», требуемой для «build/fmpz_mpoly/divides_array.lo».  Останов.
make[1]: *** Ожидание завершения заданий…
  CC  fmpz_mpoly/realloc.c
make[1]: выход из каталога «/polusfs/home/smirnov.a/fire/FIRE6/extra/fuel/extra/flint»
make: 
```*** [Makefile:66: flintLibrary] Ошибка 2

**Comment by albinahlback** [comment]
> I see a merge to the flintlib:main branch, and last time I used trunk.

Yeah, we renamed the default branch to `main` from `trunk`.

**Comment by Sander80** [comment]
It's in russian, it says in has no rule to build src/hashmap.h
I think I've seen it already, you removed it or something

**Comment by albinahlback** [comment]
> Hmm cannot built it
> 
> ```
>   CC  fmpz_mpoly/is_fmpz.c
>   CC  fmpz_mpoly/add.c
>   CC  fmpz_mpoly/mul_monomial.c
>   CC  fmpz_mpoly/gcd_cofactors.c
>   CC  fmpz_mpoly/cmp.c
>   CC  fmpz_mpoly/get_term_exp_ui.c
>   CC  fmpz_mpoly/set_term_exp_fmpz.c
>   CC  fmpz_mpoly/mul_dense.c
>   CC  fmpz_mpoly/gcd.c
> make[1]: *** Нет правила для сборки цели «src/hashmap.h», требуемой для «build/fmpz_mpoly/divides_array.lo».  Останов.
> make[1]: *** Ожидание завершения заданий…
>   CC  fmpz_mpoly/realloc.c
> make[1]: выход из каталога «/polusfs/home/smirnov.a/fire/FIRE6/extra/fuel/extra/flint»
> make: 
> ```*** [Makefile:66: flintLibrary] Ошибка 2
> ```

It complains about `hashmap.h` (I think, I cannot speak русски). Run
```
./bootstrap.sh
./configure [OPTIONS]
make clean
make
make check
...
```

**Comment by Sander80** [comment]
Yes, it works now, thank you!
That bug is gone.
Some other test of fuel on this computer is not passed however... I need to understand whether it is related to flint changes yet

**Comment by albinahlback** [comment]
Thanks for informing us, and please let us know if you believe it stems from FLINT. I will close this one for now.

**Comment by Sander80** [comment]
It's not related to this issue anyway, thank you
The crash appeared when we were initializing same flint context by multiple threads at the same time. Probably it's not supposed to happen, so I added a mutex.
