### ISSUE TITLE
Parser for multivariate rational functions?

### ISSUE THREAD

**Issue by Sander80** [flintlib/flint#1720]
Greetings.
I wanted to ask if a parser for multivariate rational functions (fmpz_mpoly_q) is somewhere in the planned list.
Now that we need it badly since we wrote our own parser for this and later even left the fmpz_mpoly_q aside keeping a pair of fmpz_mpoly for numerator anf denominator in our code, but seems like suche a parser if built-it would make sense for the project.

**Comment by fredrik-johansson** [comment]
The parsing code in ``mpoly_parse_parse`` is general enough to do this; we just need to wrap it for fractions (and ideally convert it to the new generics system so that it can be used for expression parsing for all Flint types).

**Comment by Sander80** [comment]
I see. Nested fractions can be a problem... or you can limit the possible nesting...

**Comment by fredrik-johansson** [comment]
Added in #1725.

**Comment by Sander80** [comment]
Cool!
