### ISSUE TITLE
make install fails on openbsd - wrong parameter to ldconfig, etc

### ISSUE THREAD

**Issue by dimpase** [flintlib/flint#1732]
On the master branch:

```
$ make && make install
...
 CC  ca_mat/window_init.c
 CC  ca_mat/zero.c
Building libflint.a
Building libflint.so.18.0.0
ldconfig: unknown option -- n
usage: ldconfig [-mRrsUv] [path ...]
make: *** [Makefile:425: libflint.so.18.0.0] Error 1
```

On OpenBSD instead of `-n` it should be `-m`.
It looks to be due to hardcoded `@$(LDCONFIG) -n` in `Makefile.in`.
Once this is fixed, the next problem is
```
cp: ./libflint.so: No such file or directory
gmake: *** [Makefile:861: install] Error 1
```
which is due the toolchain only creating `libflint.so.18.0.0`, but no other `libflint.so.*`.

Once I do
```
$ ln libflint.so.18.0.0 libflint.so.18.0  
$ ln libflint.so.18.0.0 libflint.so.18   
$ ln libflint.so.18.0.0 libflint.so
```
then it appears to work, and I get a notice inviting me to run `make check` before do the install.
Which is kind of weird.

**Comment by jrick** [comment]
I recently ported 3.0.1: https://github.com/openbsd/ports/tree/master/math/flintlib

Check the patches, I haven't tried it against master but it's probably a good starting point.

Or update the port to build from a git checkout.

**Comment by dimpase** [comment]
https://github.com/openbsd/ports/blob/master/math/flintlib/patches/patch-flint_pc_in is already in master here.

**Comment by jrick** [comment]
Yep, I know.  It'll be removed when the port is updated to a release with that fix in it.

**Comment by dimpase** [comment]
@jrick - by the way, can you update `libmpc` port to 1.3.1 ?

**Comment by jrick** [comment]
> @jrick - by the way, can you update `libmpc` port to 1.3.1 ?

update submitted here: https://marc.info/?l=openbsd-ports&m=170577967729359&w=2

**Comment by dimpase** [comment]
cmake build does work without patches, but it does not install `flint.pc`.

**Comment by jrick** [comment]
I had noticed that the ubuntu package did not install flint.pc at all.  So that would check out, assuming they are using cmake.

**Comment by dimpase** [comment]
> I had noticed that the ubuntu package did not install flint.pc at all. So that would check out, assuming they are using cmake.

yeah, cmake people cannot figure out how to do it properly, hard to believe, but seems to be the case.

**Comment by albinahlback** [comment]
It should be solved by now. Will wait a few hours before closing this one.

**Comment by dimpase** [comment]
on OpenBSD the symbolic links to the "real" .so should not be installed, and the latter should be installed without executable permissions, i.e. with 644, not 755 mask.

**Comment by dimpase** [comment]
as well, .a file must be installed, it's used for linking to the .so

**Comment by albinahlback** [comment]
I'm afraid my knowledge in BSD-systems are lacking. If you feel like you know what is wrong, you are always welcome to make a PR.

**Comment by dimpase** [comment]
what I know, that you cannot use a symbolic link to a .so file,  as the name of the library is hardcoded in it, and verified.
```
$ ldd /usr/local/lib/libflint.so.18.0.0                                                                                                                                                   
/usr/local/lib/libflint.so.18.0.0:
	Start            End              Type  Open Ref GrpRef Name
	0000013cc48f8000 0000013cc5913000 dlib  2    0   0      /usr/local/lib/libflint.so.18.0.0
	0000013d393d1000 0000013d39498000 rlib  0    1   0      /usr/local/lib/libmpfr.so.2.3
	0000013d5b409000 0000013d5b498000 rlib  0    2   0      /usr/local/lib/libgmp.so.11.0
	0000013cc9985000 0000013cc99b6000 rlib  0    1   0      /usr/lib/libm.so.10.1
	0000013d769f4000 0000013d76a00000 rlib  0    1   0      /usr/lib/libpthread.so.27.0
```
there is also something about versioning being based on `.so.X.Y`, so that an `libfoo.so.X.Y.Z` may be used to satisfy a dependency on `libfoo.so.X.Y`.

In particular,  you should not install symbolic links to `/usr/local/lib/libflint.so.18.0.0`, just install this file only.
