### ISSUE TITLE
name clash with Singular's  `fq_nmod_set_nmod_poly` 

### ISSUE THREAD

**Issue by dimpase** [flintlib/flint#1738]
I stumbled upon a name clash `fq_nmod_set_nmod_poly` - it's present in Singular and in Flint, see
[flintlib/flint/src/fq_nmod/set_nmod_poly.c](https://github.com/flintlib/flint/blob/3ff49ec13c9fd67214bfbca630afe9f5076a8a3e/src/fq_nmod/set_nmod_poly.c#L15), while building Singular.

See https://github.com/Singular/Singular/issues/1203
```
ld: error: duplicate symbol: fq_nmod_set_nmod_poly
>>> defined at FLINTconvert.cc:92
>>>            FLINTconvert.o:(fq_nmod_set_nmod_poly) in archive /usr/ports/singular-4.3.2/factory/.libs/libfactory.a
>>> defined at set_nmod_poly.c:17 (src/fq_nmod/set_nmod_poly.c:17)
>>>            fq_nmod_merged.o:(.text+0x28A70) in archive /usr/local/lib/libflint.a
```

**Comment by albinahlback** [comment]
I think this is an issue for Singular, no?

**Comment by dimpase** [comment]
This is actually a migration of code which was in Singular to Flint - I just thought it was mis-coordinated somehow.

Apparently it is not coordinated at all - but  fixed today in Singular.

**Comment by albinahlback** [comment]
Alright, nice to hear! So this is good to close?
