### ISSUE TITLE
Shortcut for running tests

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#1752]
Instead of having to type

``build/fmpz_mat/test/main fmpz_mat_mul``

we could allow something like

``./test fmpz_mat_mul``

This would be even more useful with wildcard support:

``./test fmpz_mat_mul_*``

**Comment by albinahlback** [comment]
Since we use Make for everything, perhaps the best thing would be to integrate it into there?

**Comment by albinahlback** [comment]
Hmm, yeah, I misunderstood. This should be possible.

**Comment by albinahlback** [comment]
For REGEX stuff, we can use PCRE2.  Should be available on most modern systems.  Will try to fix this during next week.
