### ISSUE TITLE
Document common trap in `arb_set_d`

### ISSUE THREAD

**Issue by rudolph-git-acc** [flintlib/flint#1786]
Ref. this AskSagemath-question: https://ask.sagemath.org/question/76066/ghost-numbers-when-using-arb/

When I run this simple code in my IDE:

```
    #include "flint/arb.h"
    
    int main(int argc, char **argv)
    {
    	arb_t a;
    	arb_init(a);
    	
    	slong prec;
    	prec = 256;
    	
    	arb_set_d(a, 1.1);
    	arb_printd(a, 70);
    	printf("  WRONG \n");
    	
    	arb_set_str(a, "1.1", prec);
    	arb_printd(a, 70);
    	printf("  FINE \n");
    	
    	arb_set_d(a, 1);
    	arb_printd(a, 70);
    	printf("  FINE \n");
    	
    	arb_clear(a);
    	return 0;
    }
```

I obtain:

```
1.100000000000000088817841970012523233890533447265625000000000000000000 +/- 0  WRONG 
1.100000000000000000000000000000000000000000000000000000000000000000000 +/- 1.7272e-77  FINE 
1.000000000000000000000000000000000000000000000000000000000000000000000 +/- 0  FINE 
```

Only the arb_set_d command seems to induce this issue and only for non-integer values. Is this a bug or an unavoidable effect?

**Comment by albinahlback** [comment]
I don't know what you specifically mean by "wrong" here, or a "bug".

1. `arb_set_d` will only convert a `double` to an `arb_t`. If the `double` is inexact, that's on the user -- FLINT/Arb is not a compiler.
2. `arb_set_d` will not impose some error bound since it doesn't know if the double is inexact or not. Once again, that's on the user.

As `1.1` is not representable as a dyadic rational, you should not expect Arb to give a "correct" number. It will only convert what is given to it, which is an approximation, which in turn an `arb_t` can represent.

**Comment by vneiger** [comment]
Reading the provided code and the sagemath link, I think the following addition to the answer of @albinahlback might be useful for @rudolph-git-acc  : observe what you get from the following piece of C,
```
printf("%.20f\n", 1.1);
```
It should yield ``1.10000000000000008882``. This is what is meant by "inexact" (not representable etc.) above, and this has nothing to do with arb or flint or sagemath. (Sorry for the noise if that was already clear to you.)

**Comment by albinahlback** [comment]
Yes, this should be documented. Thanks for bringing this up!

**Comment by albinahlback** [comment]
Fixed in https://github.com/flintlib/flint/commit/0c07030848bb5121ddf707d23ed34318d54328be

**Comment by rudolph-git-acc** [comment]
Sorry to be a pain, but the same issue could be induced by the following commands:

<img width="354" alt="image" src="https://github.com/flintlib/flint/assets/36714969/59a2c346-fead-4470-99ca-84ff5264d6cb">  \

<img width="334" alt="image" src="https://github.com/flintlib/flint/assets/36714969/0efa733c-5f00-425a-9b39-d6ec35692a12">  \

<img width="459" alt="image" src="https://github.com/flintlib/flint/assets/36714969/5a884552-9a6e-4cb9-a056-4a928dbfffcf"> \

The latter is often used in setting integral limits. Probably good to update the documentation for these as well.

P.S.
I believe we should be good for fmpz-types:
<img width="1100" alt="image" src="https://github.com/flintlib/flint/assets/36714969/45d75604-39a2-4377-b138-b1ba465fc324">

**Comment by edgarcosta** [comment]
`arf_set_d` does not have this issue, one is converting between two equivalent representations.
