### ISSUE TITLE
Add float (single-precision) wrappers for Arb functions

### ISSUE THREAD

**Issue by MehdiChinoune** [flintlib/flint#1798]
Only double and cdouble are provided.
Please consider providing them form float and cfloat (single-precision/32-bit). We need them to run our code on client GPUs as they only support flt32.
Also single-precision compuation runs faster than double when the required accuracy is not high.

I wish I could contribute but I don't which right parameters should I choose in https://github.com/flintlib/flint/blob/main/src/arb_fpwrap/fpwrap.c 53,1077,1024 I know 53 could be replaced by 24 and 1024 by 127. but 1077?

**Comment by albinahlback** [comment]
I suppose $1077 = 1024 + 53$.

**Comment by fredrik-johansson** [comment]
Yes, an operand smaller than $2^{-(1024 + 53)}$ rounds to zero when converted to float64 (with default rounding), so this allows for quick termination for small values.

I suspect you don't *really* need us to provide float32 versions; it should be enough to convert to float64 and back on your end. The speedup of doing float32 directly would be marginal. However, I will not object if you submit a PR that adds the float32 versions. We do also want float128, BTW.

**Comment by MehdiChinoune** [comment]
> I suspect you don't *really* need us to provide float32 versions; it should be enough to convert to float64 and back on your end. The speedup of doing float32 directly would be marginal. However, I will not object if you submit a PR that adds the float32 versions.

I mentioned above that I need it to run it on some client GPUs where the  ratio of fp64 units is about 1/24 of fp32 units. I won't bother if I run my code on CPU.

> We do also want float128, BTW.

I will consider that.

**Comment by MehdiChinoune** [comment]
It's hard to implement as It needs the developer to have a better knowledge of flint internals.
