### ISSUE TITLE
Download links are outdate @ flintlib.org

### ISSUE THREAD

**Issue by edgarcosta** [flintlib/flint#1809]
`md5sum` of github vs flintlib.org
```
b172ad8fc59cbb2fa2f2ab31bb3c61fd  flint-3.1.0(1).tar.gz
eab82c770768f0ab9e32a7b3cfc4d5fd  flint-3.1.0(1).zip
fcc36930b05da464c1a1a49b50290869  flint-3.1.0.tar.gz
cd1cb6ec3f27d88063a332aa637edd3a  flint-3.1.0.zip
```
the `(1)` version is from flintlib.org

**Comment by albinahlback** [comment]
Hmm, perhaps because I backported some stuff to the 3.1 branch. Ping @fredrik-johansson

**Comment by edgarcosta** [comment]
yeah, I think that is the reason

**Comment by edgarcosta** [comment]
is there a reason why we prefer to backport it instead of having a release patch?

**Comment by albinahlback** [comment]
> is there a reason why we prefer to backport it instead of having a release patch?

I don't know.

Btw, the commits include that you now can opt-out of `-march=native` via `--disable-arch` during configuration. That way you do not have to fiddle with the autoconf variables as I see is made in that brewing recipe.

**Comment by tornaria** [comment]
Just a +1 to make tarball releases "immutable" after they are published, i.e. make a patch release for minor changes instead of changing the existing tarball.

**Comment by tornaria** [comment]
... anyway, thanks a lot for the new release which fixes the two issues I reported.
