### ISSUE TITLE
Supply fallback ldconfig

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#185]
1) Currently we don't create a symlink for dlopen. On linux it is of the form libflint.so.13. Usually the symlink is created by ldconfig, but....

2) On some systems, even Linux ones, ldconfig is not used. So we have to create the symlinks ourselves. The precise symlinks that need creating depend on the library naming policy of the OS. For Linux it seems there are three shared libraries required, two of which are symlinks: libflint.so libflint.so.13 and libflint.so.13.5.2.

The right way to handle this is for configure to create a list of libraries that are needed depending on uname (there's 645 lines of configure in autotools dedicated to this, with a big case statement per OS), then to create a script that will install them. This script can then be called from the Makefile. (This is normally the function of libtool, but we don't want to use it.)

ldconfig should be called where it is available, since it also updates some global cache of shared libraries. Creating the symlinks isn't its only function.

libtool seems to just unconditionally create all the required symlinks regardless of what ldconfig does. This seems to be unavoidable, since for example Guix doesn't have ldconfig and yet it claims to be a Linux. So our script should probably just adopt this policy. There's no way to distinguish Guix from Debian for example, if Guix is being run on top of Debian.

**Comment by wbhart** [comment]
ldconfig is now used when making a shared library.

We also offer an LDCONFIG option to configure which allows one to use a custom ldconfig. OS's which don't have ldconfig can therefore use a script which simply copies the libraries.

It would be great if someone implemented a script for doing this to save the trouble for the user, then checked for ldconfig in configure and replaced it automatically with the script if ldconfig doesn't exist.

**Comment by fredrik-johansson** [comment]
I'm assuming that this is no longer an issue.
