### ISSUE TITLE
This simple integral appears to give the wrong result

### ISSUE THREAD

**Issue by rudolph-git-acc** [flintlib/flint#1861]
To integrate (1-x)^a * (1+x)^b over x = 0..1, I wrote the following ARB-routine:

```
/*
    Test script
*/

#include "stdlib.h"
#include "flint/acb_calc.h"
#include "flint/acb_dirichlet.h"
#include "flint/profiler.h"

// integrand (1-x)^a * (1+x)^b
int
f_integrand(acb_ptr result, const acb_t xc, void *param, slong order, slong prec)
{
	arb_t ar;
	arb_init(ar);
	
	acb_t ac, bc;
	acb_init(ac);
	acb_init(bc);

	arb_ptr(a);
	arb_ptr(b);

	a = ((arb_ptr *)(param))[0];
	b = ((arb_ptr *)(param))[1];

	//(1-x)^a
	acb_sub_si(ac, xc, 1, prec);
	acb_neg(ac, ac);
	acb_pow_arb(ac, ac, a, prec);

	//(1+x)^b
 	acb_add_si(bc, xc, 1, prec);
	acb_pow_arb(bc, bc, b, prec);
	
	acb_mul(result, ac, bc, prec);

	acb_clear(ac);
	acb_clear(bc);	

    return 0;
}

void
my_integral(arb_t result, arb_t a, arb_t b, slong prec)
{  
	arb_t ar, br;
	arb_init(ar);
	arb_init(br);
	
	acb_t ac, ai, bi;
	acb_init(ac);
	acb_init(ai);
	acb_init(bi);

	slong goal;

	acb_calc_integrate_opt_t options;
	acb_calc_integrate_opt_init(options);

	mag_t tol;
	mag_init(tol);

	goal = prec;
	mag_set_ui_2exp_si(tol, 1, -prec);

	//set lower limit at 0
	arb_set_str(ar, "0", prec);
	acb_set_arb(ai, ar);
	
	//set the upper limit at 1 - epsilon (to avoid NaN output)
	arb_one(ar);
	arb_set_str(br, "10e-100", prec);
	arb_sub(ar, br, ar, prec);
	acb_set_arb(bi, ar);

	void *param[2];
	param[0] = (void *) a;
	param[1] = (void *) b;

	acb_calc_integrate(ac, f_integrand, param, ai, bi, goal, tol, NULL, prec);
		
	acb_get_real(result, ac);
	
	mag_clear(tol);
	
	arb_clear(ar);
	arb_clear(br);

	acb_clear(ac);
	acb_clear(ai);
	acb_clear(bi);
}

int main(int argc, char *argv[])
{
    arb_t a, b, res;
    arb_init(a);
    arb_init(b);
    arb_init(res);

	slong prec;
	prec = 800;
	
	arb_set_str(a, argv[1], prec);
	arb_set_str(b, argv[2], prec);
	
	my_integral(res, a, b, prec);
	
	arb_printn(res, 120, ARB_STR_NO_RADIUS);
	printf("\n");

    arb_clear(a);
    arb_clear(b);
    arb_clear(res);
    flint_cleanup();
    return 0;  
} 
```

The program takes two inputs a and b and works well for most choices. However when I take a=0.5 and b=0.5 it yields: `-0.796113019377273535466199796601602...` instead of the correct outcome `Pi/4 = 0.78539816339744830961566...`.  Grateful for any guidance on whether I did something wrong here or a way to circumvent this issue.

**Comment by albinahlback** [comment]
> ```
> 	//set the upper limit at 1 - epsilon (to avoid NaN output)
> 	arb_one(ar);
> 	arb_set_str(br, "10e-100", prec);
> 	arb_sub(ar, br, ar, prec);
> 	acb_set_arb(bi, ar);
> ```

You set `ar = 1`, `br = \epsilon`, then push `ar <- br - ar`, so `ar = \epsilon - 1 = -(1 - \epsilon)`. Hence, you have to negate the result to get the result you where looking for.

**Comment by albinahlback** [comment]
And it is not a holomorphic function on [0, 1], so I suppose that explains the small difference in values.

**Comment by albinahlback** [comment]
So if you read the [documentation](https://flintlib.org/doc/acb_calc.html), it basically says that it if the order is 1 and the input contains points of which it is not holomorphic, then it needs to return some non-finite result.

So when adjusting for this, I do get the correct result.

**Comment by fredrik-johansson** [comment]
Indeed, see ``acb_pow_analytic`` and ``acb_sqrt_analytic`` and how they are used in ``examples/integrals.c``.

**Comment by rudolph-git-acc** [comment]
Thanks both for your swift responses. Using` acb_pow_analytic` does the trick and it all works perfectly now!
