### ISSUE TITLE
Build error: `Undefined symbols: "_aligned_alloc"`

### ISSUE THREAD

**Issue by barracuda156** [flintlib/flint#1905]
```
[100%] Linking C shared library lib/libflint.dylib
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/flint.dir/link.txt --verbose=ON
/opt/local/bin/gcc-mp-13 -pipe -Os -DNDEBUG -I/opt/local/include -arch ppc -arch ppc -mmacosx-version-min=10.6 -dynamiclib -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -compatibility_version 19.0.0 -current_version 19.0.0 -o lib/libflint.19.0.0.dylib -install_name @rpath/libflint.19.dylib @CMakeFiles/flint.dir/objects1.rsp @CMakeFiles/flint.dir/objects2.rsp  -Wl,-rpath,/opt/local/lib /opt/local/lib/libopenblas.dylib -lm /opt/local/lib/libmpfr.dylib /opt/local/lib/libgmp.dylib
Undefined symbols:
  "_aligned_alloc", referenced from:
      __flint_aligned_alloc in memory_manager.c.o
     (maybe you meant: _flint_aligned_alloc)
ld: symbol(s) not found
```

`aligned_alloc` is not universally supported. Ideally there should be a check, and if no support detected, `posix_memalign` or `malloc` are to be used as fallbacks.

Could this be fixed?

**Comment by barracuda156** [comment]
https://github.com/flintlib/flint/commit/cb15d66cfc4f5f43ee9adc8b90f12a5f2d0489bb commit made an assumption that `aligned_alloc` is available everywhere but on Windows. That is incorrect.

**Comment by barracuda156** [comment]
If I just remove `# define HAVE_ALIGNED_ALLOC 1` from `cmake_config.h.in`, everything builds fine then (because the code already has fallback, but it is just not allowed now).

@albinahlback Could you please help here?

**Comment by albinahlback** [comment]
Can you print the whole CMake log?

**Comment by barracuda156** [comment]
> Can you print the whole CMake log?

Sure, allow me a few min. I will re-run the build from the master rather than 3.1.2 release.

**Comment by albinahlback** [comment]
I just mean the configuration part.

**Comment by barracuda156** [comment]
> I just mean the configuration part.

[CMakeConfigureLog.txt](https://github.com/flintlib/flint/files/14884436/CMakeConfigureLog.txt)

This is in fact expected not to work, since `aligned_alloc` does not exist in macOS up to 10.14 or so.

P. S. I replaced native optflag due to https://github.com/flintlib/flint/pull/1906 (flag is unrelated to `aligned_alloc`, but just in case someone notices).

**Comment by albinahlback** [comment]
Looks like you are building on macOS. You should get the following message when configuring for it, although it is not printed to the log file:
```
CMake Warning at CMakeLists.txt:16 (message):
  Detected system is not Windows.  Please use the Autotools configuration
  along with the Makefile instead as it is more up-to-date.  Read INSTALL.
```
Can you confirm that you get this message during the configuration?

**Comment by barracuda156** [comment]
Yes, I do. (But this is not my port, so I cannot unilaterally switch it in Macports to another building system.)

**Comment by albinahlback** [comment]
Okay, then report the issue there. To my knowledge, there is no place where the documentation implies that CMake would work just as fine as Autotools. If it does, please let me know. But as for now, this is not something that we will fix.

**Comment by barracuda156** [comment]
@albinahlback Ok, with autotools configure handles `aligned_alloc` correctly:
```
checking if alloca works... yes
checking for aligned_alloc... no
checking for _aligned_malloc... no
```
Thank you for insisting on this :)
I will bring the matter to Macports, it should be easier to switch than to fix CMake build anyway.
