### ISSUE TITLE
Error finding PkgConfig while installing Flint package using CMake on Windows

### ISSUE THREAD

**Issue by AkhilAkkapelli** [flintlib/flint#2039]
I am trying to install the Flint package (version 3.1.3-p1) by following the steps mentioned on their website. I am using CMake for the build process. However, I am encountering an error related to `PkgConfig`. Below is the command I ran and the error message I received:

**Command:**
`cmake .. -DBUILD_SHARED_LIBS=ON`

**Error Message:**
```
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Hint: The project() command has not yet been called. It sets up system-specific search paths.
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- Checking if system is strongly ordered - yes
CMake Error at C:/Users/akhil/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/site-packages/cmake/data/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
C:/Users/akhil/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/site-packages/cmake/data/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
C:/Users/akhil/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0/LocalCache/local-packages/Python312/site-packages/cmake/data/share/cmake-3.30/Modules/FindPkgConfig.cmake:114 (find_package_handle_standard_args)
CMakeLists.txt:74 (find_package)
-- Configuring incomplete, errors occurred!
```

It seems that `PkgConfig` is not found. How can I resolve this issue on a Windows system? Is there a specific way to install or configure `PkgConfig` so that CMake can find it? Any help would be appreciated!

**Environment:**
- Windows 11
- CMake version: 3.30 (installed via Python)
- Trying to build Flint package version 3.1.3-p1

**Comment by albinahlback** [comment]
Use the main branch instead.

I might have put `pkg-config` stuff in their a while back, but it should be removed in the main branch. Check out through Github instead.

Please reopen if the issue remain.
