### ISSUE TITLE
Gentoo Linux: sci-mathematics/flint-3.1.3_p1 QA Notice: Package triggers severe warnings which indicate that it may exhibit random runtime failures.

### ISSUE THREAD

**Issue by Arniiiii** [flintlib/flint#2044]
```
 * Messages for package sci-mathematics/flint-3.1.3_p1:

 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/tmp/portage/sci-mathematics/flint-3.1.3_p1/work/flint-3.1.3-p1/src/bernoulli/mod_p_harvey.c:390:34: warning: iteration 64 invokes undefined behavior [-Waggressive-loop-optimizations]
 * /var/tmp/portage/sci-mathematics/flint-3.1.3_p1/work/flint-3.1.3-p1/src/bernoulli/mod_p_harvey.c:656:34: warning: iteration 64 invokes undefined behavior [-Waggressive-loop-optimizations]
 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://www.flintlib.org/
```

from https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-faggressive-loop-optimizations : 
`
-faggressive-loop-optimizations
`
`    This option tells the loop optimizer to use language constraints to derive bounds for the number of iterations of a loop. This assumes that loop code does not invoke undefined behavior by for example causing signed integer overflows or out-of-bound array accesses. The bounds for the number of iterations of a loop are used to guide loop unrolling and peeling and loop exit test optimizations. This option is enabled by default.
`

lzip tarball (remove ____.txt )  `how_it_was_called.txt emerge_--info.txt /var/tmp/portage/sci-mathematics/flint-3.1.3_p1/{build-info/**,files/**,temp/**,work/**.log} /var/lib/portage/** /etc/portage/** /var/log/portage/elog/sci-mathematics/flint-3.1.3_p1:20240803-103955.log`
 :  [flint-3.1.3_p1_qa_notice.tar.lz____.txt](https://github.com/user-attachments/files/16479342/flint-3.1.3_p1_qa_notice.tar.lz____.txt)

**Comment by albinahlback** [comment]
It should never be able to do `FLINT_BITS` or more number of iterations in those loops; I believe it should only be able to do `FLINT_BITS` - 2 iterations at most. Could you try to insert
```c
if (bits >= FLINT_BITS)
    __builtin_unreachable();
```
before said loops to see if that fixes the issue? However, the compiler should be smart enough to fix that on its own.

If the issue persists, please give some more information such as compiler and version etc. Will close this for now.
