### ISSUE TITLE
Make failure under CentOS stream 8

### ISSUE THREAD

**Issue by by-bian** [flintlib/flint#2054]
Here is the details.  I can't figure out the reason.

$ make -j 20

<.........>

src/fmpz_mpoly_factor/gcd_brown_threaded.c:353:33: 警告: ‘#pragma GCC diagnostic’ の後に不明なオプションです [-Wpragmas]
 # pragma GCC diagnostic ignored "-Wdangling-pointer"
                                 ^~~~~~~~~~~~~~~~~~~~
  CC  fmpz_mpoly_factor/gcd_hensel.c
  CC  fmpz_mpoly_factor/set.c
  CC  fmpz_mpoly_factor/compression.c
  CC  fmpz_mod_mpoly_factor/eval.c
  CC  fmpz_mod_mpoly_factor/zip_helpers.c
  CC  fmpz_mod_mpoly_factor/bpoly_factor_smprime.c
  CC  fmpz_mod_mpoly_factor/gcd_algo.c
  CC  fmpz_mod_mpoly_factor/factor_squarefree.c
  CC  fmpz_mod_mpoly_factor/polyun.c
  CC  fmpz_mod_mpoly_factor/irred_smprime_zippel.c
  CC  fmpz_mod_mpoly_factor/get_set_lead0.c
  CC  fmpz_mod_mpoly_factor/cmp.c
  CC  fmpz_mod_mpoly_factor/set_nmod_mpoly_factor.c
  CC  fmpz_mod_mpoly_factor/fmpz_mod_pow_cache.c
  CC  fmpz_mod_mpoly_factor/io.c
  CC  fmpz_mod_mpoly_factor/factor_content.c
  CC  fmpz_mod_mpoly_factor/mpolyu.c
  CC  fmpz_mod_mpoly_factor/gcd_zippel2.c
  CC  fmpz_mod_mpoly_factor/mpolyn.c
  CC  fmpz_mod_mpoly_factor/gcd_brown.c
  CC  fmpz_mod_mpoly_factor/stack.c
  CC  fmpz_mod_mpoly_factor/inlines.c
  CC  fmpz_mod_mpoly_factor/realloc.c
  CC  fmpz_mod_mpoly_factor/lcc_wang.c
  CC  fmpz_mod_mpoly_factor/fmpz_mod_poly_vec.c
  CC  fmpz_mod_mpoly_factor/fmpz_mod_mat_extras.c
  CC  fmpz_mod_mpoly_factor/mpoly_hlift_zippel.c
  CC  fmpz_mod_mpoly_factor/sort.c
  CC  fmpz_mod_mpoly_factor/polyu3_mod_hlift.c
  CC  fmpz_mod_mpoly_factor/bpoly_hlift.c
  CC  fmpz_mod_mpoly_factor/mpolyn_divides.c
  CC  fmpz_mod_mpoly_factor/fmpz_mod_poly_extras.c
  CC  fmpz_mod_mpoly_factor/mpoly_pfrac.c
  CC  fmpz_mod_mpoly_factor/clear.c
  CC  fmpz_mod_mpoly_factor/irred_smprime_zassenhaus.c
  CC  fmpz_mod_mpoly_factor/mpoly_hlift.c
  CC  fmpz_mod_mpoly_factor/interp.c
  CC  fmpz_mod_mpoly_factor/fit_length.c
  CC  fmpz_mod_mpoly_factor/gcd_zippel.c
cc1: 警告: 認識できないコマンドラインオプション ‘-Wno-stringop-overread’ です
  CC  fmpz_mod_mpoly_factor/factor.c
  CC  fmpz_mod_mpoly_factor/mpolyv.c
  CC  fmpz_mod_mpoly_factor/fmpz_mod_bpoly.c
  CC  fmpz_mod_mpoly_factor/expand.c
  CC  fmpz_mod_mpoly_factor/gcd_hensel.c
  CC  fmpz_mod_mpoly_factor/irred_smprime_wang.c
  CC  fmpz_mod_mpoly_factor/compression.c
  CC  fmpq_mpoly_factor/factor_squarefree.c
  CC  fmpq_mpoly_factor/init.c
  CC  fmpq_mpoly_factor/realloc.c
  CC  fmpq_mpoly_factor/fit_length.c
  CC  fmpq_mpoly_factor/swap_fmpz_mpoly_factor.c
  CC  fmpq_mpoly_factor/inlines.c
  CC  fmpq_mpoly_factor/sort.c
  CC  fmpq_mpoly_factor/factor_make_integral.c
  CC  fmpq_mpoly_factor/clear.c
  CC  fmpq_mpoly_factor/factor_make_monic.c
  CC  fmpq_mpoly_factor/factor.c
  CC  fmpq_mpoly_factor/expand.c
  CC  fq_nmod_mpoly_factor/eval.c
  CC  fq_nmod_mpoly_factor/factor_squarefree.c
  CC  fq_nmod_mpoly_factor/polyu3_hlift.c
  CC  fq_nmod_mpoly_factor/polyun.c
  CC  fq_nmod_mpoly_factor/n_bpoly_fq_factor_smprime.c
  CC  fq_nmod_mpoly_factor/polyu.c
  CC  fq_nmod_mpoly_factor/irred_smprime_zippel.c
  CC  fq_nmod_mpoly_factor/get_set_lead0.c
  CC  fq_nmod_mpoly_factor/io.c
  CC  fq_nmod_mpoly_factor/init.c
  CC  fq_nmod_mpoly_factor/irred_lgprime.c
  CC  fq_nmod_mpoly_factor/mpoly_hlift.c
  CC  fq_nmod_mpoly_factor/get_constant_fq_nmod.c
  CC  fq_nmod_mpoly_factor/realloc.c
  CC  fq_nmod_mpoly_factor/get_exp_si.c
  CC  fq_nmod_mpoly_factor/n_bpoly_hlift.c
  CC  fq_nmod_mpoly_factor/factor_content.c
  CC  fq_nmod_mpoly_factor/mpolyv.c
  CC  fq_nmod_mpoly_factor/cmp.c
  CC  fq_nmod_mpoly_factor/n_bpoly_fq.c
  CC  fq_nmod_mpoly_factor/inlines.c
  CC  fq_nmod_mpoly_factor/lcc_wang.c
  CC  fq_nmod_mpoly_factor/sort.c
  CC  fq_nmod_mpoly_factor/one.c
  CC  fq_nmod_mpoly_factor/mpoly_pfrac.c
  CC  fq_nmod_mpoly_factor/clear.c
  CC  fq_nmod_mpoly_factor/irred_smprime_zassenhaus.c
  CC  fq_nmod_mpoly_factor/fit_length.c
  CC  fq_nmod_mpoly_factor/factor.c
  CC  fq_nmod_mpoly_factor/expand.c
  CC  fq_nmod_mpoly_factor/n_bpoly_fq_factor_lgprime.c
  CC  fq_nmod_mpoly_factor/append.c
  CC  fq_nmod_mpoly_factor/set.c
  CC  fq_nmod_mpoly_factor/irred_smprime_wang.c
  CC  fq_nmod_mpoly_factor/compression.c
  CC  fq_zech_mpoly_factor/eval.c
  CC  fq_zech_mpoly_factor/bpoly_factor_smprime.c
  CC  fq_zech_mpoly_factor/polyun.c
  CC  fq_zech_mpoly_factor/polyu.c
  CC  fq_zech_mpoly_factor/irred_smprime_zippel.c
  CC  fq_zech_mpoly_factor/get_set_lead0.c
  CC  fq_zech_mpoly_factor/init.c
  CC  fq_zech_mpoly_factor/mpoly_hlift.c
  CC  fq_zech_mpoly_factor/realloc.c
  CC  fq_zech_mpoly_factor/io.c
  CC  fq_zech_mpoly_factor/mpoly_univar.c
  CC  fq_zech_mpoly_factor/get_set_is_fq_nmod_poly.c
  CC  fq_zech_mpoly_factor/tpoly.c
  CC  fq_zech_mpoly_factor/polyu3_hlift.c
  CC  fq_zech_mpoly_factor/lcc_wang.c
  CC  fq_zech_mpoly_factor/bpoly.c
  CC  fq_zech_mpoly_factor/bpoly_hlift.c
  CC  fq_zech_mpoly_factor/mpoly_pfrac.c
  CC  fq_zech_mpoly_factor/clear.c
  CC  fq_zech_mpoly_factor/irred_smprime_zassenhaus.c
  CC  fq_zech_mpoly_factor/fit_length.c
  CC  fq_zech_mpoly_factor/factor.c
  CC  fq_zech_mpoly_factor/irred_smprime_wang.c
  CC  fq_zech_mpoly_factor/mpolyv.c
  CC  fft/adjust.c
  CC  fft/fft_truncate.c
  CC  fft/convolution_precache.c
  CC  fft/combine_bits.c
  CC  fft/inlines.c
  CC  fft/mul_fft_main.c
  CC  fft/fft_mfa_truncate_sqrt2_inner.c
  CC  fft/mulmod_2expp1.c
  CC  fft/butterfly_rshB.c
  CC  fft/mul_mfa_truncate_sqrt2.c
  CC  fft/ifft_mfa_truncate_sqrt2.c
  CC  fft/ifft_truncate_sqrt2.c
  CC  fft/ifft_radix2.c
  CC  fft/fermat_to_mpz.c
  CC  fft/div_2expmod_2expp1.c
  CC  fft/ifft_truncate.c
  CC  fft/fft_radix2.c
  CC  fft/butterfly_lshB.c
  CC  fft/mul_truncate_sqrt2.c
  CC  fft/convolution.c
  CC  fft/mul_2expmod_2expp1.c
  CC  fft/ifft_negacyclic.c
  CC  fft/fft_mfa_truncate_sqrt2.c
  CC  fft/fft_negacylic.c
  CC  fft/adjust_sqrt2.c
  CC  fft/fft_truncate_sqrt2.c
  CC  fft/negmod_2expp1.c
  CC  fft/normmod_2expp1.c
  CC  fft/split_bits.c
  CC  fft_small/default_ctx.c
  CC  fft_small/mpn_mul.c
  CC  fft_small/mpn_helpers.c
  CC  fft_small/sd_fft_ctx.c
  CC  fft_small/nmod_poly_mul.c
  CC  fft_small/fmpz_poly_mul.c
  CC  fft_small/mulmod_statisfies_bounds.c
  CC  fft_small/sd_fft.c
  CC  fft_small/sd_ifft.c
  CC  fmpz_poly_q/set_str.c
  CC  fmpz_poly_q/get_str.c
  CC  fmpz_poly_q/print.c
  CC  fmpz_poly_q/get_str_pretty.c
In file included from src/fft_small/mpn_mul.c:17:
./src/crt_helpers.h: 関数 ‘_addcarry_ulong’ 内:
./src/crt_helpers.h:33:10: エラー: implicit declaration of function ‘_addcarry_u64’; did you mean ‘_addcarry_ulong’? [-Werror=implicit-function-declaration]
     cf = _addcarry_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~
          _addcarry_ulong
./src/crt_helpers.h: 関数 ‘_subborrow_ulong’ 内:
./src/crt_helpers.h:43:10: エラー: implicit declaration of function ‘_subborrow_u64’; did you mean ‘_subborrow_ulong’? [-Werror=implicit-function-declaration]
     cf = _subborrow_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~~
          _subborrow_ulong
  CC  fmpz_poly_q/is_canonical.c
  CC  fmpz_poly_q/inv.c
In file included from src/fft_small/mpn_helpers.c:13:
./src/crt_helpers.h: 関数 ‘_addcarry_ulong’ 内:
./src/crt_helpers.h:33:10: エラー: implicit declaration of function ‘_addcarry_u64’; did you mean ‘_addcarry_ulong’? [-Werror=implicit-function-declaration]
     cf = _addcarry_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~
          _addcarry_ulong
In file included from src/fft_small/fmpz_poly_mul.c:18:
./src/crt_helpers.h: 関数 ‘_addcarry_ulong’ 内:
./src/crt_helpers.h:33:10: エラー: implicit declaration of function ‘_addcarry_u64’; did you mean ‘_addcarry_ulong’? [-Werror=implicit-function-declaration]
     cf = _addcarry_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~
          _addcarry_ulong
./src/crt_helpers.h: 関数 ‘_subborrow_ulong’ 内:
./src/crt_helpers.h:43:10: エラー: implicit declaration of function ‘_subborrow_u64’; did you mean ‘_subborrow_ulong’? [-Werror=implicit-function-declaration]
     cf = _subborrow_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~~
          _subborrow_ulong
  CC  fmpz_poly_q/init.c
./src/crt_helpers.h: 関数 ‘_subborrow_ulong’ 内:
./src/crt_helpers.h:43:10: エラー: implicit declaration of function ‘_subborrow_u64’; did you mean ‘_subborrow_ulong’? [-Werror=implicit-function-declaration]
     cf = _subborrow_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~~
          _subborrow_ulong
In file included from src/fft_small/nmod_poly_mul.c:17:
./src/crt_helpers.h: 関数 ‘_addcarry_ulong’ 内:
./src/crt_helpers.h:33:10: エラー: implicit declaration of function ‘_addcarry_u64’; did you mean ‘_addcarry_ulong’? [-Werror=implicit-function-declaration]
     cf = _addcarry_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~
          _addcarry_ulong
./src/crt_helpers.h: 関数 ‘_subborrow_ulong’ 内:
./src/crt_helpers.h:43:10: エラー: implicit declaration of function ‘_subborrow_u64’; did you mean ‘_subborrow_ulong’? [-Werror=implicit-function-declaration]
     cf = _subborrow_u64(cf, (long long unsigned int)(x),
          ^~~~~~~~~~~~~~
          _subborrow_ulong
  CC  fmpz_poly_q/print_pretty.c
  CC  fmpz_poly_q/pow.c
  CC  fmpz_poly_q/canonicalise.c
  CC  fmpz_poly_q/add.c
  CC  fmpz_poly_q/addmul.c
  CC  fmpz_poly_q/inlines.c
  CC  fmpz_poly_q/mul.c
src/fft_small/mpn_helpers.c: トップレベル:
cc1: 警告: 認識できないコマンドラインオプション ‘-Wno-stringop-overread’ です
cc1: some warnings being treated as errors
make: *** [Makefile:615: build/fft_small/mpn_helpers.lo] エラー 1
make: *** 未完了のジョブを待っています....
src/fft_small/nmod_poly_mul.c: トップレベル:
cc1: 警告: 認識できないコマンドラインオプション ‘-Wno-stringop-overread’ です
cc1: some warnings being treated as errors
make: *** [Makefile:615: build/fft_small/nmod_poly_mul.lo] エラー 1
src/fft_small/fmpz_poly_mul.c: トップレベル:
cc1: 警告: 認識できないコマンドラインオプション ‘-Wno-stringop-overread’ です
cc1: some warnings being treated as errors
make: *** [Makefile:615: build/fft_small/fmpz_poly_mul.lo] エラー 1
src/fft_small/mpn_mul.c: トップレベル:
cc1: 警告: 認識できないコマンドラインオプション ‘-Wno-stringop-overread’ です
cc1: some warnings being treated as errors
make: *** [Makefile:615: build/fft_small/mpn_mul.lo] エラー 1
rm build/mpn_extras/broadwell/sqrhigh_basecase_odd_pic.s build/mpn_extras/broadwell/sqr_hard_pic.s build/mpn_extras/broadwell/mulhigh_basecase_pic.s build/mpn_extras/broadwell/mulhigh_normalised_hard_pic.s build/mpn_extras/broadwell/sqrhigh_hard_pic.s build/mpn_extras/broadwell/mul_hard_pic.s build/mpn_extras/broadwell/mulhigh_hard_pic.s build/mpn_extras/broadwell/sqrhigh_basecase_even_pic.s

**Comment by albinahlback** [comment]
1. What compiler are you using?
2. How did you configure FLINT, and what was the output?

**Comment by by-bian** [comment]
@albinahlback 

> 1. What compiler are you using?
> 2. How did you configure FLINT, and what was the output?

Thanks for your kind reply.

1. The compiler used here is GUN Make 4.2.1.
2. The details of configuring show below:

$ ./configure --with-gmp=/mnt/users/bybian/anaconda3/envs/my_env/

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for inline... inline
checking whether byte ordering is bigendian... no
checking if memory is strongly-ordered... yes
checking gmp.h usability... yes
checking gmp.h presence... yes
checking for gmp.h... yes
checking if version of GMP is greater than 6.2.1... yes
checking if GMP defines mp_limb_t as unsigned long long int... no
checking mpfr.h usability... yes
checking mpfr.h presence... yes
checking for mpfr.h... yes
checking if version of MPFR is greater than 4.1.0... yes
checking for desired ABI... 64
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking pthread_np.h usability... no
checking pthread_np.h presence... no
checking for pthread_np.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for library containing atan2... -lm
checking for library containing __gmpz_init... -lgmp
checking for library containing __gmpn_gcd_11... none required
checking for library containing __gmpn_div_q... none required
checking for library containing __gmpn_mul_basecase... none required
checking for library containing __gmpn_modexact_1_odd... none required
checking for library containing __gmpn_addmul_2... none required
checking for library containing mpfr_init... -lmpfr
checking for library containing mpfr_round_p... none required
checking for library containing mpfr_mulhigh_n... none required
checking for library containing mpfr_sqrhigh_n... none required
checking whether gcc accepts -pthread... yes
checking if cpu_set_t is supported... yes
checking if alloca works... yes
checking for aligned_alloc... yes
checking for _aligned_malloc... no
checking whether gcc accepts -Werror=unknown-warning-option... no
checking whether gcc accepts -Wall... yes
checking whether gcc accepts -Wno-stringop-overread... yes
checking whether gcc accepts -Wno-stringop-overflow... yes
checking whether gcc accepts -Werror=implicit-function-declaration... yes
checking whether gcc accepts -O3... yes
checking whether gcc accepts -march=native... yes
checking whether gcc accepts -std=c11... yes
checking whether gcc accepts -pedantic... yes
checking for host architecture... skylake-avx512
checking immintrin.h usability... yes
checking immintrin.h presence... yes
checking for immintrin.h... yes
checking if system have required x86_64 instruction set for fft_small... yes
checking if system can use FLINT's fft_small module... yes
checking if system uses System V ABI... yes
checking if ADX instruction set is supported by CPU... yes
checking if system can use FLINT's assembly... yes
checking for suitable m4... m4
checking how to switch to text section... .text
checking how to switch to data section... .data
checking for assembler label suffix... :
checking for assembler global directive... .globl
checking for assembler global directive attribute...
checking if globals are prefixed by underscore... no
checking how to switch to read-only data section...     .section        .rodata
checking for assembler .type directive... .type $1,@$2
checking for assembler .size directive... .size $1,$2
checking for assembler local label prefix... .L
checking for assembler byte directive... .byte
checking if .align assembly directive is logarithmic... no
checking if the .align directive accepts an 0x90 fill in .text... yes
checking for assembler COFF type directives... no
creating config.m4
configure: creating ./config.status
config.status: creating src/gmpcompat.h
config.status: creating src/fft_tuning.h
config.status: creating src/fmpz/fmpz.c
config.status: creating Makefile
config.status: creating flint.pc
config.status: creating src/flint.h
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: creating src/flint-config.h
config.status: src/flint-config.h is unchanged
config.status: executing libtool commands

**Comment by albinahlback** [comment]
Based off your output, I believe you are compiling with GCC. Not sure which version, though. Can you give me the output of `gcc --version`?

**Comment by albinahlback** [comment]
I should probably make so that it prints version of the compiler in the configuration.

**Comment by albinahlback** [comment]
Is there a specific reason for not using a recent version of GCC? Dangling pointers where introduced in GCC 12.1, two years ago.

**Comment by albinahlback** [comment]
I'm closing this as I believe you should be able to upgrade your compiler.
