### ISSUE TITLE
Tuning thresholds for nmod vec/mat scalar multiplication

### ISSUE THREAD

**Issue by vneiger** [flintlib/flint#2059]
The threshold 10 in the following functions seems somewhat arbitrary; on two machines tested, it is either quite too high or quite too low:
- ``_nmod_vec_scalar_mul_nmod``
- ``_nmod_vec_scalar_addmul_nmod``
- ``nmod_mat_scalar_mul`` (also, here, why the requirement ``A->mod.n < UWORD_HALF`` when applying ``n_mulmod_shoup``?)

Since this threshold apparently differs a lot depending on the machine (*), we may add some tuning mechanism for this.

(*) presumably mostly depending on the speed of its "div" instruction which is the main component of Shoup's precomputation in ``n_mulmod_shoup_precomp``.

**Comment by fredrik-johansson** [comment]
IIRC the 10 is tuned for zen3. We ought to put the appropriate value for each architecture in ``flint-mparam.h``.

The ``A->mod.n < UWORD_HALF`` check could be replaced with ``NMOD_BITS(mod) != FLINT_BITS``.

**Comment by vneiger** [comment]
> IIRC the 10 is tuned for zen3. We ought to put the appropriate value for each architecture in `flint-mparam.h`.

Thanks for the suggestion. I can give it a try with the few architectures I have at hand. If I understand well, let me know if not, I should simply put some threshold in all the ``mpn_extras/XXX/flint-mparam.h`` files, say 
``#define FLINT_MULMOD_SHOUP_THRESHOLD 10``
(the current value) for the architectures I cannot test, and values I get from experiments on the architectures I do have access to.

> The A->mod.n < UWORD_HALF check could be replaced with NMOD_BITS(mod) != FLINT_BITS.

Ok, I suspected this. Or there is a macro ``NMOD_CAN_USE_SHOUP`` which does the same test. I will do this within PR #2055 .

**Comment by albinahlback** [comment]
> If I understand well, let me know if not, I should simply put some threshold in all the `mpn_extras/XXX/flint-mparam.h` files, say `#define FLINT_MULMOD_SHOUP_THRESHOLD 10` (the current value) for the architectures I cannot test, and values I get from experiments on the architectures I do have access to.

Correct. As every architecture has to have a corresponding value, I suspect you have to guess this value for some architectures. In that case, just leave a comment that it was guessed.

**Comment by vneiger** [comment]
> > If I understand well, let me know if not, I should simply put some threshold in all the `mpn_extras/XXX/flint-mparam.h` files, say `#define FLINT_MULMOD_SHOUP_THRESHOLD 10` (the current value) for the architectures I cannot test, and values I get from experiments on the architectures I do have access to.
> 
> Correct. As every architecture has to have a corresponding value, I suspect you have to guess this value for some architectures. In that case, just leave a comment that it was guessed.

And for the architectures I can access to but do not find (in x86-64: I should be able to test haswell, icelake, zen4), do I simply create a folder with ``flint-mparam.h`` and populate it with things obtained from the few ``tune/`` files? or is there some configure/makefile modification to do?

**Comment by vneiger** [comment]
Added the macro within PR #2055   and put values for zen4 and icelake  (will add Skylake later today).
