### ISSUE TITLE
Segfault in fq_default tests on Cygwin

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#2070]
Following #2047 and/or #2050 there is a problem in the fq_default tests on Cygwin/GCC: https://github.com/flintlib/flint/actions/runs/10773322840/job/29872862221

Not sure why; the new code doesn't look platform-dependent in any way.

**Comment by albinahlback** [comment]
Could be that it invokes some bug in some dependency of `fq_default`. Hard to know though, especially since Cygwin is almost never used.

**Comment by albinahlback** [comment]
I think there might be a bug in `fq_default_ctx_init_randtest`, but I have to investigate this more to give a definite answer.
