### ISSUE TITLE
Document `fmpz_mod_poly_scalar_mul_ui` ?

### ISSUE THREAD

**Issue by fingolfin** [flintlib/flint#2079]
I noticed that there exists a function `fmpz_mod_poly_scalar_mul_ui` (and also `_fmpz_mod_poly_scalar_mul_ui`) which seems to be an undocumented sibling to `fmpz_mod_poly_scalar_mul_fmpz`.

Is there a reason this is undocumented? Is it safe to use it / would it be useful to document it?

**Comment by albinahlback** [comment]
Looking at the code, it should be very safe to use!

I would guess that it was quickly implemented since it internally promotes to fmpz. Should be documented, though.
