### ISSUE TITLE
Truncation of nfloat to double

### ISSUE THREAD

**Issue by renehiemstra** [flintlib/flint#2106]
Great library! However, it's not clear how I can truncate and map an nfloat back to a native double representation. Could you elaborate?

**Comment by albinahlback** [comment]
Suppose you have `nfloat_ptr xp` and `gr_ctx_t ctx`. To get the mantissa, you could do
```c
NFLOAT_D(xp)[NFLOAT_CTX_NLIMBS(ctx) - 1]
```
and shift it accordingly (this is assuming a 64-bit computer). However, you still have to shift it accordingly afterwards. This will be a 64 bit mantissa, with the most significant bit set (which is implicit in the `double` representation).

You get the sign bit via `NFLOAT_SGNBIT(xp) & 1`.

You get the exponent via `NFLOAT_EXP(x)` (which you have to translate into the `double representation`).

**Comment by renehiemstra** [comment]
Got it. Thanks!
