### ISSUE TITLE
Make a --minimal option for configure

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#390]
We could add a configure option to Flint which adds only a minimal list of subdirs to the the build. I'm not sure what that list would include, but for sure it wouldn't include finite fields, any of the poly_mat directories, and perhaps others.

I'm not sure how we would stop people installing a minimal build systemwide. We still want to be able to install to a prefix (e.g. for Nemo), so we can't just disable make install with a minimal build.

We could also have a --glorified-calculator option which only adds fmpz and ulong_extras to the build. :-)

**Comment by albinahlback** [comment]
I don't this is feasible in regards to maintainability. If someone disagrees with me, feel free to reopen.
