### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint#529]
It would be interesting to see the results of testing Flint with gcov.

**Comment by fredrik-johansson** [comment]
Bump. This is not urgent, but the results would still be interesting.

I had no success setting this up the last time I tried.

**Comment by fredrik-johansson** [comment]
@albinahlback Thanks to your clean new build system, this is really simple now:

Add ``-fprofile-arcs -ftest-coverage`` to CFLAGS

``make -j check``

``lcov --capture --directory build --output-file build/coverage.info``

``genhtml build/coverage.info --output-directory build``

Want to add something like this to the makefile (e.g. ``./configure --test-coverage && make coverage`` )? We could also add coverage reports to the CI with something like codecov.

A minor issue is that the test programs are subject to the coverage report as well. Actually, including the test programs can be useful to find problems with the test code. But mostly it just drags down the coverage numbers since we never enter the FAIL blocks. Maybe we can exclude those blocks with ``--exclude-branches-by-pattern`` or somesuch?

**Comment by fredrik-johansson** [comment]
I put this in the Makefile since there wasn't much to it.

It remains to enable automated reports through CI.

**Comment by albinahlback** [comment]
I will try to automate this after I fix the versioning thing for macOS.
