### ISSUE TITLE
Remove nmod_poly_powmod_mpz_blah and related functions

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#682]
There are numerous functions in nmod_poly and presumably also fmpz_mod_poly which use mpz's instead of fmpz's. These should be eliminated. The fmpz versions of many of them now exist and we should switch over to those.

**Comment by albinahlback** [comment]
I have been very annoyed by these functions. I can fix this.

**Comment by wbhart** [comment]
Thanks.
