### ISSUE TITLE
fmpz_mod_mat should (probably) take a context object

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#779]
This is in line with the proposed changes to fmpz_mod_poly and seems sensible given the potential size of the context object.

**Comment by fredrik-johansson** [comment]
I think I would like to do this sooner rather than later.

@albinahlback If we make this compatibility-breaking change now, can you fix Nemo?

**Comment by albinahlback** [comment]
Yes

**Comment by fredrik-johansson** [comment]
Fixed.
