### ISSUE TITLE
Add more documentation links

### ISSUE THREAD

**Issue by wbhart** [flintlib/flint#996]
W Stein writes:

> I would humbly suggest that the FLINT landing page have a link at the top to

> http://flintlib.org/doc/

> The FLINT website begins "FLINT is extensively documented" (very true!); however, as far as I can tell, there's no link to the docs or other mention of documentation anywhere on the website, except in the downloads section (http://www.flintlib.org/downloads.html). This is a possibly surprising place to find docs, since they aren't something you download anymore (it used to be that they were, when they were only available in pdf).

> Also the page http://www.flintlib.org/features.html is kind of like the table of contents of a reference manual of FLINT functionality, except (1) there is no link to the documentation on that page, and (2) there are no links from any of the features listed there either.   For a while I thought I should just get inspired by  http://www.flintlib.org/features.html, then dive into the source code to figure out how to use something, which is how some projects are that are too busy to write proper docs.

**Comment by albinahlback** [comment]
Just reminding that a PR has been merged (https://github.com/wbhart/flintwebpage/pull/1). Think the site needs to reload, but maybe my browser is displaying the site incorrectly.

**Comment by wbhart** [comment]
I think the issue is that the website is no longer hosted from a git
repository. I guess it has to be changed on the actual website.

I'll try to look into that.

**Comment by wbhart** [comment]
I've now added doc links on the features and index page. I'll leave this ticket open though, as it may still be nice to make some of the titles on the features page into links, as William kind of suggests. I don't have time to do it right now.

**Comment by albinahlback** [comment]
I see this as completed. There is a link at the top of https://flintlib.org/, and there is a link in the README as well, wihch I think is "lagom". Feel free to reopen if you disagree.
